import Foundation

// MARK: - Localization Support

struct Localization {
    private static let dict: [String: [String: String]] = [
        "General Settings": ["English": "General Settings", "Tiếng Việt": "Cài đặt chung"],
        "General": ["English": "General", "Tiếng Việt": "Chung"],
        "API Keys": ["English": "API Keys", "Tiếng Việt": "API Key"],
        "Language": ["English": "Language", "Tiếng Việt": "Ngôn ngữ"],
        "Launch at Login": ["English": "Launch at Login", "Tiếng Việt": "Khởi động cùng máy"],
        "Hover to Open": ["English": "Hover to Open", "Tiếng Việt": "Mở khi rê chuột"],
        "Hover Open Delay": ["English": "Hover Open Delay", "Tiếng Việt": "Độ trễ mở khi rê chuột"],
        "Adjust how long the pointer must stay over the notch before it opens.": ["English": "Adjust how long the pointer must stay over the notch before it opens.", "Tiếng Việt": "Chỉnh thời gian con trỏ cần đứng trên notch trước khi nó mở ra."],
        "Accent Color": ["English": "Accent Color", "Tiếng Việt": "Màu nhấn"],
        "Choose the shared accent used for Talk controls and settings buttons.": ["English": "Choose the shared accent used for Talk controls and settings buttons.", "Tiếng Việt": "Chọn màu nhấn chung cho các nút trong Talk và phần cài đặt."],
        "Ocean": ["English": "Ocean", "Tiếng Việt": "Biển xanh"],
        "Mint": ["English": "Mint", "Tiếng Việt": "Bạc hà"],
        "Gold": ["English": "Gold", "Tiếng Việt": "Vàng"],
        "Coral": ["English": "Coral", "Tiếng Việt": "San hô"],
        "Rose": ["English": "Rose", "Tiếng Việt": "Hồng"],
        "Cycle": ["English": "Cycle", "Tiếng Việt": "Chu kỳ"],
        "Version": ["English": "Version", "Tiếng Việt": "Phiên bản"],
        "Focus": ["English": "Focus", "Tiếng Việt": "Tập trung"],
        "Focus Sound": ["English": "Focus Sound", "Tiếng Việt": "Âm đổi focus"],
        "Short": ["English": "Short", "Tiếng Việt": "Nghỉ ngắn"],
        "Long": ["English": "Long", "Tiếng Việt": "Nghỉ dài"],
        "Websites": ["English": "Websites", "Tiếng Việt": "Trang web"],
        "Website Access Mode": ["English": "Website Access Mode", "Tiếng Việt": "Chế độ truy cập trang web"],
        "Use all except blocked": ["English": "Use all except blocked", "Tiếng Việt": "Dùng tất cả trừ trang bị chặn"],
        "Only use allowed": ["English": "Only use allowed", "Tiếng Việt": "Chỉ dùng trang được phép"],
        "All websites work except domains in Blocked Websites.": [
            "English": "All websites work except domains in Blocked Websites.",
            "Tiếng Việt": "Tất cả trang web hoạt động, trừ các domain trong danh sách bị chặn.",
        ],
        "Only domains in Allowed Websites work during focus.": [
            "English": "Only domains in Allowed Websites work during focus.",
            "Tiếng Việt": "Chỉ các domain trong danh sách được cho phép hoạt động khi tập trung.",
        ],
        "Blocked Websites": ["English": "Blocked Websites", "Tiếng Việt": "Trang web bị chặn"],
        "Add website...": ["English": "Add website...", "Tiếng Việt": "Thêm trang web..."],
        "No websites blocked yet.": ["English": "No websites blocked yet.", "Tiếng Việt": "Chưa có trang web bị chặn."],
        "Enter one domain per line. Example: youtube.com": [
            "English": "Enter one domain per line. Example: youtube.com",
            "Tiếng Việt": "Nhập mỗi domain trên một dòng. Ví dụ: youtube.com",
        ],
        "%d domains synced to Chrome extension": [
            "English": "%d domains synced to Chrome extension",
            "Tiếng Việt": "%d domain đã đồng bộ sang extension Chrome",
        ],
        "Chrome reads this list live while focus is running.": [
            "English": "Chrome reads this list live while focus is running.",
            "Tiếng Việt": "Chrome đọc danh sách này trực tiếp khi focus đang chạy.",
        ],
        "Round": ["English": "Round", "Tiếng Việt": "Vòng"],
        "Time": ["English": "Time", "Tiếng Việt": "Thời gian"],
        "Stats": ["English": "Stats", "Tiếng Việt": "Thống kê"],
        "Settings": ["English": "Settings", "Tiếng Việt": "Cài đặt"],
        "Last 7 Days": ["English": "Last 7 Days", "Tiếng Việt": "7 ngày qua"],
        "Focus on": ["English": "Focus on", "Tiếng Việt": "Tập trung ngày"],
        "Break": ["English": "Break", "Tiếng Việt": "Giải lao"],
        "Pause": ["English": "Pause", "Tiếng Việt": "Tạm dừng"],
        "Resume": ["English": "Resume", "Tiếng Việt": "Tiếp tục"],
        "Start Focus": ["English": "Start Focus", "Tiếng Việt": "Bắt đầu tập trung"],
        "Start": ["English": "Start", "Tiếng Việt": "Bắt đầu"],
        "Reset": ["English": "Reset", "Tiếng Việt": "Đặt lại"],
        "Skip": ["English": "Skip", "Tiếng Việt": "Bỏ qua"],
        "Next": ["English": "Next", "Tiếng Việt": "Tiếp theo"],
        "Correct": ["English": "Correct", "Tiếng Việt": "Đúng"],
        "Incorrect": ["English": "Incorrect", "Tiếng Việt": "Chưa đúng"],
        "Answer": ["English": "Answer", "Tiếng Việt": "Đáp án"],
        "Explanation": ["English": "Explanation", "Tiếng Việt": "Giải thích"],
        "Translation": ["English": "Translation", "Tiếng Việt": "Dịch nghĩa"],
        "Accuracy": ["English": "Accuracy", "Tiếng Việt": "Độ chính xác"],
        "AI quiz: %d ready": [
            "English": "AI quiz: %d ready",
            "Tiếng Việt": "AI quiz: %d câu sẵn sàng",
        ],
        "AI Part 5/6: %d questions": [
            "English": "AI Part 5/6: %d questions",
            "Tiếng Việt": "AI Part 5/6: %d câu",
        ],
        "AI unavailable · meaning quiz": [
            "English": "AI unavailable · meaning quiz",
            "Tiếng Việt": "AI không sẵn · quiz nghĩa từ",
        ],
        "Hover for translation": [
            "English": "Hover for translation",
            "Tiếng Việt": "Hover để xem bản dịch",
        ],
        "Leisure": ["English": "Leisure", "Tiếng Việt": "Giải trí"],
        "+%d min leisure": [
            "English": "+%d min leisure",
            "Tiếng Việt": "+%d phút giải trí",
        ],
        "Break +%d min from study": [
            "English": "Break +%d min from study",
            "Tiếng Việt": "Nghỉ +%d phút từ học",
        ],
        "Auto Start Breaks": ["English": "Auto Start Breaks", "Tiếng Việt": "Tự chạy khi nghỉ"],
        "Auto Start Pomo": ["English": "Auto Start Pomo", "Tiếng Việt": "Tự chạy Pomo"],
        "Auto Breaks": ["English": "Auto Breaks", "Tiếng Việt": "Tự bật nghỉ"],
        "Auto Pomo": ["English": "Auto Pomo", "Tiếng Việt": "Tự bật Pomo"],
        "Focus Session": ["English": "Focus Session", "Tiếng Việt": "Đang tập trung"],
        "Short Break": ["English": "Short Break", "Tiếng Việt": "Giải lao ngắn"],
        "Long Break": ["English": "Long Break", "Tiếng Việt": "Giải lao dài"],
        "Pomodoro": ["English": "Pomodoro", "Tiếng Việt": "Tập trung"],
        "Mon": ["English": "Mon", "Tiếng Việt": "Th 2"],
        "Tue": ["English": "Tue", "Tiếng Việt": "Th 3"],
        "Wed": ["English": "Wed", "Tiếng Việt": "Th 4"],
        "Thu": ["English": "Thu", "Tiếng Việt": "Th 5"],
        "Fri": ["English": "Fri", "Tiếng Việt": "Th 6"],
        "Sat": ["English": "Sat", "Tiếng Việt": "Th 7"],
        "Sun": ["English": "Sun", "Tiếng Việt": "CN"],
        "Back": ["English": "Back", "Tiếng Việt": "Quay lại"],
        "Save": ["English": "Save", "Tiếng Việt": "Lưu"],
        "Profile": ["English": "Profile", "Tiếng Việt": "Hồ sơ"],
        "Tools": ["English": "Tools", "Tiếng Việt": "Công cụ"],
        "Skills": ["English": "Skills", "Tiếng Việt": "Kỹ năng"],
        "Common": ["English": "General", "Tiếng Việt": "Chung"],
        "Push to Talk hint": [
            "English": "Used only in Push to Talk mode while Gemini Live is connected. Shortcuts must include at least one modifier key.",
            "Tiếng Việt": "Chỉ dùng ở chế độ Nhấn để nói khi Gemini Live đang kết nối. Phím tắt cần có ít nhất một phím bổ trợ (⌘, ⌥, ⌃ hoặc ⇧).",
        ],
        "System Prompt": ["English": "System Prompt", "Tiếng Việt": "Lời nhắc hệ thống"],
        "New Agent": ["English": "New Agent", "Tiếng Việt": "Agent mới"],
        "Delete Agent": ["English": "Delete Agent", "Tiếng Việt": "Xóa Agent"],
        "Voice": ["English": "Voice", "Tiếng Việt": "Giọng nói"],
        "Thinking": ["English": "Thinking", "Tiếng Việt": "Suy nghĩ"],
        "Media Resolution": ["English": "Media Resolution", "Tiếng Việt": "Độ chi tiết hình ảnh"],
        "Agent": ["English": "Agent", "Tiếng Việt": "Trợ lý"],
        "Manage keys": ["English": "Manage keys", "Tiếng Việt": "Quản lý Key"],
        "Online": ["English": "Online", "Tiếng Việt": "Đang online"],
        "Ready": ["English": "Ready", "Tiếng Việt": "Sẵn sàng"],
        "Readiness": ["English": "Readiness", "Tiếng Việt": "Độ sẵn sàng"],
        "Selected agent": ["English": "Selected agent", "Tiếng Việt": "Trợ lý đang chọn"],
        "Ready to start a live conversation.": ["English": "Ready to start a live conversation.", "Tiếng Việt": "Sẵn sàng bắt đầu trò chuyện trực tiếp."],
        "is ready": ["English": "is ready", "Tiếng Việt": "đã sẵn sàng"],
        "Screen": ["English": "Screen", "Tiếng Việt": "Màn hình"],
        "Start Talking": ["English": "Start Talking", "Tiếng Việt": "Bắt đầu nói"],
        "Voice-first Talk surface": ["English": "Voice-first Talk surface", "Tiếng Việt": "Giao diện ưu tiên giọng nói"],
        "Connect": ["English": "Connect", "Tiếng Việt": "Kết nối"],
        "Disconnect": ["English": "Disconnect", "Tiếng Việt": "Ngắt kết nối"],
        "End": ["English": "End", "Tiếng Việt": "Kết thúc"],
        "Open Mic": ["English": "Open Mic", "Tiếng Việt": "Mic"],
        "Push to Talk": ["English": "Push to Talk", "Tiếng Việt": "Nhấn để nói"],
        "Push to Talk key": ["English": "Push to Talk key", "Tiếng Việt": "Phím bấm để nói"],
        "Hold": ["English": "Hold", "Tiếng Việt": "Giữ"],
        "Listening": ["English": "Listening", "Tiếng Việt": "Đang nghe"],
        "Mic": ["English": "Mic", "Tiếng Việt": "Mic"],
        "Muted": ["English": "Muted", "Tiếng Việt": "Tắt tiếng"],
        "Subs": ["English": "Subs", "Tiếng Việt": "Phụ đề"],
        "Subs Off": ["English": "Subs Off", "Tiếng Việt": "Phụ đề Tắt"],
        "Subs Auto": ["English": "Subs Auto", "Tiếng Việt": "Phụ đề Tự ẩn"],
        "Subs Pin": ["English": "Subs Pin", "Tiếng Việt": "Phụ đề Ghim"],
        "Type": ["English": "Type", "Tiếng Việt": "Nhập"],
        "Suggest": ["English": "Suggest", "Tiếng Việt": "Gợi ý"],
        "Auto Type": ["English": "Auto Type", "Tiếng Việt": "Nhập tự ẩn"],
        "Auto Collapse Type": ["English": "Auto Collapse Type", "Tiếng Việt": "Nhập tự thu nhỏ"],
        "Always Show Type": ["English": "Always Show Type", "Tiếng Việt": "Luôn hiện ô nhập"],
        "Hide Type": ["English": "Hide Type", "Tiếng Việt": "Ẩn ô nhập"],
        "Auto Hide Captions": ["English": "Auto Hide Captions", "Tiếng Việt": "Phụ đề tự ẩn"],
        "Pin Captions": ["English": "Pin Captions", "Tiếng Việt": "Ghim phụ đề"],
        "Hide Captions": ["English": "Hide Captions", "Tiếng Việt": "Ẩn phụ đề"],
        "Hide": ["English": "Hide", "Tiếng Việt": "Ẩn"],
        "Pin": ["English": "Pin", "Tiếng Việt": "Ghim"],
        "Context": ["English": "Context", "Tiếng Việt": "Ngữ cảnh"],
        "Gemini is listening...": ["English": "Gemini is listening...", "Tiếng Việt": "Đang nghe..."],
        "Thinking...": ["English": "Thinking...", "Tiếng Việt": "Đang nghĩ..."],
        "Delete Agent?": ["English": "Delete Agent?", "Tiếng Việt": "Xóa trợ lý này?"],
        "Cancel": ["English": "Cancel", "Tiếng Việt": "Hủy"],
        "Delete": ["English": "Delete", "Tiếng Việt": "Xóa"],
        "Disable": ["English": "Disable", "Tiếng Việt": "Tắt"],
        "Back to Home": ["English": "Back to Home", "Tiếng Việt": "Trang chủ"],
        "Nothing Playing": ["English": "Nothing Playing", "Tiếng Việt": "Không có nội dung"],
        "System Media": ["English": "System Media", "Tiếng Việt": "Hệ thống"],
        "Done": ["English": "Done", "Tiếng Việt": "Xong"],
        "Gemini Live needs a Gemini API key.": ["English": "Gemini Live needs a Gemini API key.", "Tiếng Việt": "Gemini Live cần một API Key."],
        "Keys are not entered in the notch. Use the menu bar or Manage keys below.": ["English": "Keys are not entered in the notch. Use the menu bar or Manage keys below.", "Tiếng Việt": "Key không thể nhập tại Notch. Hãy dùng Menu Bar hoặc nút Quản lý Key bên dưới."],
        "Approve Command": ["English": "Approve Command", "Tiếng Việt": "Phê duyệt lệnh"],
        "Deny": ["English": "Deny", "Tiếng Việt": "Từ chối"],
        "Gemini API Key": ["English": "Gemini API Key", "Tiếng Việt": "Gemini API Key"],
        "Saved": ["English": "Saved", "Tiếng Việt": "Đã lưu"],
        "Save API key to local": ["English": "Save API key to local", "Tiếng Việt": "Lưu API Key vào máy"],
        "Allow Once": ["English": "Allow Once", "Tiếng Việt": "Cho phép 1 lần"],
        "Once": ["English": "Once", "Tiếng Việt": "1 lần"],
        "Always Exact": ["English": "Always Exact", "Tiếng Việt": "Luôn lệnh này"],
        "Exact": ["English": "Exact", "Tiếng Việt": "Lệnh này"],
        "Always": ["English": "Always", "Tiếng Việt": "Luôn"],
        "Enable All": ["English": "Enable All", "Tiếng Việt": "Bật tất cả"],
        "Disable All": ["English": "Disable All", "Tiếng Việt": "Tắt tất cả"],
        "All skills": ["English": "All skills", "Tiếng Việt": "Tất cả Skill"],
        "All tools": ["English": "All tools", "Tiếng Việt": "Tất cả công cụ"],
        "Core Tools": ["English": "Core Tools", "Tiếng Việt": "Công cụ cốt lõi"],
        "New Skill": ["English": "New Skill", "Tiếng Việt": "Kỹ năng mới"],
        "No skills installed": ["English": "No skills installed", "Tiếng Việt": "Chưa cài kỹ năng nào"],
        "Share App Window": ["English": "Share App Window", "Tiếng Việt": "Chia sẻ cửa sổ app"],
        "Share Full Screen": ["English": "Share Full Screen", "Tiếng Việt": "Chia sẻ toàn màn hình"],
        "Share Selected Region": ["English": "Share Selected Region", "Tiếng Việt": "Chia sẻ vùng chọn"],
        "Share Camera": ["English": "Share Camera", "Tiếng Việt": "Chia sẻ camera"],
        "Stop Sharing": ["English": "Stop Sharing", "Tiếng Việt": "Dừng chia sẻ"],
        "Camera": ["English": "Camera", "Tiếng Việt": "Camera"],
        "Region": ["English": "Region", "Tiếng Việt": "Vùng"],
        "Name": ["English": "Name", "Tiếng Việt": "Tên"],
        "Agent name (optional)": ["English": "Agent name (optional)", "Tiếng Việt": "Tên trợ lý (không bắt buộc)"],
        "Edit System Prompt": ["English": "Edit System Prompt", "Tiếng Việt": "Sửa lời nhắc hệ thống"],
        "No skills": ["English": "No skills", "Tiếng Việt": "Không có Skill"],
        "No tools": ["English": "No tools", "Tiếng Việt": "Không có công cụ"],
        "Clear": ["English": "Clear", "Tiếng Việt": "Xóa trắng"],
        "Change Photo": ["English": "Change Photo", "Tiếng Việt": "Đổi ảnh"],
        "Default": ["English": "Default", "Tiếng Việt": "Mặc định"],
        "Search": ["English": "Search", "Tiếng Việt": "Tìm kiếm"],
        "Read": ["English": "Read", "Tiếng Việt": "Đọc"],
        "Write": ["English": "Write", "Tiếng Việt": "Ghi"],
        "List": ["English": "List", "Tiếng Việt": "Liệt kê"],
        "Find": ["English": "Find", "Tiếng Việt": "Tìm file"],
        "Grep": ["English": "Grep", "Tiếng Việt": "Tìm nội dung"],
        "Edit": ["English": "Edit", "Tiếng Việt": "Sửa"],
        "Calendar": ["English": "Calendar", "Tiếng Việt": "Lịch"],
        "Clipboard": ["English": "Clipboard", "Tiếng Việt": "Bảng tạm"],
        "App": ["English": "App", "Tiếng Việt": "Ứng dụng"],
        "Media": ["English": "Media", "Tiếng Việt": "Phát lại"],
        "Screenshot": ["English": "Screenshot", "Tiếng Việt": "Chụp màn hình"],
        "Browser": ["English": "Browser", "Tiếng Việt": "Trình duyệt"],
        "Local File Search": ["English": "Local File Search", "Tiếng Việt": "Tìm file cục bộ"],
        "Show Result": ["English": "Show Result", "Tiếng Việt": "Hiển thị kết quả"],
        "Skill Writer": ["English": "Skill Writer", "Tiếng Việt": "Tạo Skill"],
        "Exec": ["English": "Exec", "Tiếng Việt": "Chạy lệnh"],
        "Off": ["English": "Off", "Tiếng Việt": "Tắt"],
        "Low": ["English": "Low", "Tiếng Việt": "Thấp"],
        "Medium": ["English": "Medium", "Tiếng Việt": "Vừa"],
        "High": ["English": "High", "Tiếng Việt": "Cao"],
        "Auto-start Breaks": ["English": "Auto-start Breaks", "Tiếng Việt": "Tự động bắt đầu nghỉ"],
        "Auto-start Pomo": ["English": "Auto-start Pomo", "Tiếng Việt": "Tự động bắt đầu Pomodoro"],
        "tools": ["English": "tools", "Tiếng Việt": "công cụ"],
        "skills": ["English": "skills", "Tiếng Việt": "kỹ năng"],
        "Auto Hide": ["English": "Auto Hide", "Tiếng Việt": "Tự ẩn"],
        "Quit Notch": ["English": "Quit Notch", "Tiếng Việt": "Thoát Notch"],
        "Hide Notch": ["English": "Hide Notch", "Tiếng Việt": "Ẩn Notch"],
        "Show Notch": ["English": "Show Notch", "Tiếng Việt": "Hiện Notch"],
        "Show on One Screen": ["English": "Show on One Screen", "Tiếng Việt": "Chỉ hiện trên một màn hình"],
        "Show on All Screens": ["English": "Show on All Screens", "Tiếng Việt": "Hiển thị trên tất cả màn hình"],
        "Reposition": ["English": "Reposition", "Tiếng Việt": "Định vị lại"],
        "Settings…": ["English": "Settings…", "Tiếng Việt": "Cài đặt…"],
        "Quit": ["English": "Quit", "Tiếng Việt": "Thoát"],
        "Invisible": ["English": "Invisible", "Tiếng Việt": "Trong suốt"],
        "Fullscreen": ["English": "Fullscreen", "Tiếng Việt": "Toàn màn hình"],
        "Invisible Always": ["English": "Invisible Always", "Tiếng Việt": "Luôn ẩn"],
        "Screen Display": ["English": "Screen Display", "Tiếng Việt": "Hiển thị màn hình"],
        "One Screen": ["English": "One", "Tiếng Việt": "Một"],
        "All Screens": ["English": "All", "Tiếng Việt": "Tất cả"],
        "User Profile": ["English": "User Profile", "Tiếng Việt": "Hồ sơ cá nhân"],
        "Memory": ["English": "Memory", "Tiếng Việt": "Bộ nhớ"],
        "User Profile (USER.md)": ["English": "User Profile (USER.md)", "Tiếng Việt": "Hồ sơ cá nhân (USER.md)"],
        "Memory (MEMORY.md)": ["English": "Memory (MEMORY.md)", "Tiếng Việt": "Bộ nhớ (MEMORY.md)"],
        "Save User Profile": ["English": "Save User Profile", "Tiếng Việt": "Lưu hồ sơ"],
        "Save Memory": ["English": "Save Memory", "Tiếng Việt": "Lưu bộ nhớ"],
        "Mode": ["English": "Mode", "Tiếng Việt": "Chế độ"],
        "Zen": ["English": "Zen", "Tiếng Việt": "Chìm đắm"],
        "Strict": ["English": "Strict", "Tiếng Việt": "Kỷ luật nghỉ"],
        "Sound": ["English": "Sound", "Tiếng Việt": "Âm thanh"],
        "Streak": ["English": "Streak", "Tiếng Việt": "Chuỗi đúng"],
        "Today": ["English": "Today", "Tiếng Việt": "Hôm nay"],
        "Sessions": ["English": "Sessions", "Tiếng Việt": "Phiên"],
        "Average": ["English": "Average", "Tiếng Việt": "Trung bình"],
        "What are you working on?": ["English": "What are you working on?", "Tiếng Việt": "Bạn đang làm việc gì?"],
        "Tasks": ["English": "Tasks", "Tiếng Việt": "Nhiệm vụ"],
        "Add": ["English": "Add", "Tiếng Việt": "Thêm"],
        "No tasks yet": ["English": "No tasks yet", "Tiếng Việt": "Chưa có nhiệm vụ nào"],
        "Open tasks": ["English": "Open tasks", "Tiếng Việt": "Nhiệm vụ đang mở"],
        "Completed tasks": ["English": "Completed tasks", "Tiếng Việt": "Nhiệm vụ đã hoàn thành"],
        "Subscription": ["English": "Subscription", "Tiếng Việt": "Đăng ký"],
        "Gemini Live": ["English": "Gemini Live", "Tiếng Việt": "Gemini Live"],
        "Gemini Account": ["English": "Gemini Account", "Tiếng Việt": "Tài khoản Gemini"],
        "Talk": ["English": "Talk", "Tiếng Việt": "Trò chuyện"],
        "Floating orb window": [
            "English": "Floating orb window",
            "Tiếng Việt": "Cửa sổ orb nổi",
        ],
        "Show floating orb window when connected": [
            "English": "Show floating orb when session is connected",
            "Tiếng Việt": "Hiện cửa sổ orb nổi khi phiên đang kết nối",
        ],
        "Orb always on top": [
            "English": "Orb always on top",
            "Tiếng Việt": "Orb luôn nổi trên cửa sổ thường",
        ],
        "Show Notch in Dock when orb visible": [
            "English": "Show Notch in Dock while orb window is visible",
            "Tiếng Việt": "Hiện Notch trong Dock khi đang có cửa sổ orb",
        ],
        "Orb appearance": [
            "English": "Orb appearance",
            "Tiếng Việt": "Kiểu orb",
        ],
        "Orb style Ice": [
            "English": "Ice",
            "Tiếng Việt": "Băng",
        ],
        "Orb style Ember": [
            "English": "Ember",
            "Tiếng Việt": "Than lửa",
        ],
        "Orb style Nebula": [
            "English": "Nebula",
            "Tiếng Việt": "Tinh vân",
        ],
        "Orb style Aurora": [
            "English": "Aurora",
            "Tiếng Việt": "Cực quang",
        ],
        "Orb style Mono": [
            "English": "Mono",
            "Tiếng Việt": "Đơn sắc",
        ],
        "Orb style Particle Wave": [
            "English": "Particle Wave",
            "Tiếng Việt": "Sóng hạt",
        ],
        "Orb menu": ["English": "Orb", "Tiếng Việt": "Orb"],
        "Orb menu Show in Dock": [
            "English": "Show Notch in Dock while orb visible",
            "Tiếng Việt": "Hiện Notch trong Dock khi đang có orb",
        ],
        "Orb menu Open Talk settings": [
            "English": "Open Talk settings…",
            "Tiếng Việt": "Mở cài đặt Talk…",
        ],
        "Appearance": ["English": "Appearance", "Tiếng Việt": "Giao diện"],
        "Notch Pro": ["English": "Notch Pro", "Tiếng Việt": "Notch Pro"],
        "Subscribed": ["English": "Subscribed", "Tiếng Việt": "Đã đăng ký"],
        "Not subscribed": ["English": "Not subscribed", "Tiếng Việt": "Chưa đăng ký"],
        "Subscribe": ["English": "Subscribe", "Tiếng Việt": "Đăng ký"],
        "Restore Purchases": ["English": "Restore Purchases", "Tiếng Việt": "Khôi phục giao dịch"],
        "Connection Method": ["English": "Connection Method", "Tiếng Việt": "Kiểu kết nối"],
        "Account": ["English": "Account", "Tiếng Việt": "Tài khoản"],
        "Notch Account": ["English": "Notch Account", "Tiếng Việt": "Tài khoản Notch"],
        "Not signed in": ["English": "Not signed in", "Tiếng Việt": "Chưa đăng nhập"],
        "Manage your Notch account and Pro subscription.": [
            "English": "Manage your Notch account and Pro subscription.",
            "Tiếng Việt": "Quản lý tài khoản Notch và gói Pro.",
        ],
        "Your account has Notch Pro access.": [
            "English": "Your account has Notch Pro access.",
            "Tiếng Việt": "Tài khoản của bạn có quyền Notch Pro.",
        ],
        "Upgrade to Notch Pro to unlock Talk.": [
            "English": "Upgrade to Notch Pro to unlock Talk.",
            "Tiếng Việt": "Nâng cấp Notch Pro để mở khóa Talk.",
        ],
        "Sign in to verify Pro access and sync your subscription.": [
            "English": "Sign in to verify Pro access and sync your subscription.",
            "Tiếng Việt": "Đăng nhập để xác minh quyền Pro và đồng bộ gói đăng ký.",
        ],
        "Managed server uses your Notch Account.": [
            "English": "Managed server uses your Notch Account.",
            "Tiếng Việt": "Máy chủ được quản lý dùng Tài khoản Notch của bạn.",
        ],
        "Sign in and manage Pro from the Account tab.": [
            "English": "Sign in and manage Pro from the Account tab.",
            "Tiếng Việt": "Đăng nhập và quản lý Pro trong tab Tài khoản.",
        ],
        "Open Account Settings": [
            "English": "Open Account Settings",
            "Tiếng Việt": "Mở cài đặt Tài khoản",
        ],
        "Choose how Notch connects to Gemini Live across the app.": [
            "English": "Choose how Notch connects to Gemini Live across the app.",
            "Tiếng Việt": "Chọn cách Notch kết nối tới Gemini Live cho toàn bộ ứng dụng.",
        ],
        "Most people should use Notch Account. API key mode is best for advanced setups.": [
            "English": "Most people should use Notch Account. API key mode is best for advanced setups.",
            "Tiếng Việt": "Hầu hết mọi người nên dùng Tài khoản Notch. Chế độ API key phù hợp hơn cho thiết lập nâng cao.",
        ],
        "Your Gemini API Key": ["English": "Your Gemini API Key", "Tiếng Việt": "Gemini API Key của bạn"],
        "Save API key": ["English": "Save API key", "Tiếng Việt": "Lưu API key"],
        "This key is stored locally on your Mac and used directly by Notch.": [
            "English": "This key is stored locally on your Mac and used directly by Notch.",
            "Tiếng Việt": "Key này được lưu cục bộ trên máy Mac và được Notch dùng trực tiếp.",
        ],
        "Use secure browser sign-in. Notch will complete OAuth 2.0 + PKCE automatically.": [
            "English": "Use secure browser sign-in. Notch will complete OAuth 2.0 + PKCE automatically.",
            "Tiếng Việt": "Dùng đăng nhập an toàn trên trình duyệt. Notch sẽ tự hoàn tất OAuth 2.0 + PKCE.",
        ],
        "No URL or token setup required.": [
            "English": "No URL or token setup required.",
            "Tiếng Việt": "Không cần nhập URL hay token.",
        ],
        "Sign in here once and Talk will reuse this session everywhere in the app.": [
            "English": "Sign in here once and Talk will reuse this session everywhere in the app.",
            "Tiếng Việt": "Đăng nhập một lần ở đây, Talk sẽ dùng lại phiên này ở mọi nơi trong app.",
        ],
        "Continue in your browser. Notch will finish OAuth sign-in automatically.": [
            "English": "Continue in your browser. Notch will finish OAuth sign-in automatically.",
            "Tiếng Việt": "Tiếp tục trong trình duyệt. Notch sẽ tự hoàn tất đăng nhập OAuth.",
        ],
        "Use your own Gemini key if you prefer to connect directly.": [
            "English": "Use your own Gemini key if you prefer to connect directly.",
            "Tiếng Việt": "Dùng Gemini key riêng nếu bạn muốn kết nối trực tiếp.",
        ],
        "Signed in as": ["English": "Signed in as", "Tiếng Việt": "Đăng nhập với"],
        "Log in": ["English": "Log in", "Tiếng Việt": "Đăng nhập"],
        "Sign up": ["English": "Sign up", "Tiếng Việt": "Tạo tài khoản"],
        "Sign out": ["English": "Sign out", "Tiếng Việt": "Đăng xuất"],
        "Open Settings Tab": ["English": "Open Settings Tab", "Tiếng Việt": "Mở tab Cài đặt"],
        "Notch Pro is required to use Talk.": [
            "English": "Notch Pro is required to use Talk.",
            "Tiếng Việt": "Cần Notch Pro để dùng Talk.",
        ],
        "Notch Pro is required to use the hosted Gemini Live server.": [
            "English": "Notch Pro is required to use the hosted Gemini Live server.",
            "Tiếng Việt": "Cần Notch Pro để dùng máy chủ Gemini Live được Notch cung cấp.",
        ],
        "Create account on the web": [
            "English": "Create account on the web",
            "Tiếng Việt": "Tạo tài khoản trên web",
        ],
        "Sign in on the web": [
            "English": "Sign in on the web",
            "Tiếng Việt": "Đăng nhập trên web",
        ],
        "After you sign in on the web, Notch will return automatically.": [
            "English": "After you sign in on the web, Notch will return automatically.",
            "Tiếng Việt": "Sau khi bạn đăng nhập trên web, Notch sẽ tự quay lại.",
        ],
        "Copy-token flow (recommended): on the web sign-in page, the token is copied after login — open Notch, tap Paste from clipboard, then Sign in with token. Or sign in below with email and password.": [
            "English": "Copy-token flow (recommended): on the web sign-in page, the token is copied after login — open Notch, tap Paste from clipboard, then Sign in with token. Or sign in below with email and password.",
            "Tiếng Việt": "Nên dùng: sau khi đăng nhập trên web, token được copy — mở Notch, bấm Dán từ clipboard, rồi Đăng nhập bằng token. Hoặc đăng nhập bên dưới bằng email và mật khẩu.",
        ],
        "Session token": [
            "English": "Session token",
            "Tiếng Việt": "Token phiên",
        ],
        "Paste from clipboard": [
            "English": "Paste from clipboard",
            "Tiếng Việt": "Dán từ clipboard",
        ],
        "Sign in with token": [
            "English": "Sign in with token",
            "Tiếng Việt": "Đăng nhập bằng token",
        ],
        "Invalid or expired session token.": [
            "English": "Invalid or expired session token.",
            "Tiếng Việt": "Token không hợp lệ hoặc đã hết hạn.",
        ],
        "Buy Notch Pro": ["English": "Buy Notch Pro", "Tiếng Việt": "Mua Notch Pro"],
        "Refresh Pro status": [
            "English": "Refresh Pro status",
            "Tiếng Việt": "Cập nhật trạng thái Pro",
        ],
        "Sign in or refresh your Notch account to verify Pro access for Talk.": [
            "English": "Sign in or refresh your Notch account to verify Pro access for Talk.",
            "Tiếng Việt": "Đăng nhập hoặc cập nhật tài khoản Notch để xác minh quyền Pro cho Talk.",
        ],
        "Notch Pro access could not be verified. Refresh your account to continue using Talk.": [
            "English": "Notch Pro access could not be verified. Refresh your account to continue using Talk.",
            "Tiếng Việt": "Không thể xác minh quyền Notch Pro. Hãy cập nhật tài khoản để tiếp tục dùng Talk.",
        ],
        "Offline Pro grace period is active.": [
            "English": "Offline Pro grace period is active.",
            "Tiếng Việt": "Đang dùng thời gian gia hạn Pro khi offline.",
        ],
        "Pro status is expired. Refresh your account to verify access.": [
            "English": "Pro status is expired. Refresh your account to verify access.",
            "Tiếng Việt": "Trạng thái Pro đã hết hạn. Hãy cập nhật tài khoản để xác minh quyền truy cập.",
        ],
        "Pro status has not been verified yet.": [
            "English": "Pro status has not been verified yet.",
            "Tiếng Việt": "Trạng thái Pro chưa được xác minh.",
        ],
        "Weekly Activity": ["English": "Weekly Activity", "Tiếng Việt": "Hoạt động hàng tuần"],
        "Session Timing": ["English": "Session Timing", "Tiếng Việt": "Thời gian phiên"],
        "Overview": ["English": "Overview", "Tiếng Việt": "Tổng quan"],
        "Session": ["English": "Session", "Tiếng Việt": "Phiên"],
        "Sound & Alerts": ["English": "Sound & Alerts", "Tiếng Việt": "Âm thanh & Cảnh báo"],
        "Cloud Ranking": ["English": "Cloud Ranking", "Tiếng Việt": "Xếp hạng đám mây"],
        "Pomodoro lengths, weekly activity, and ranking privacy": [
            "English": "Pomodoro lengths, weekly activity, and ranking privacy",
            "Tiếng Việt": "Độ dài pomodoro, hoạt động tuần, và quyền riêng tư xếp hạng",
        ],
        "Pomodoro lengths and long-break cycle": [
            "English": "Pomodoro lengths and long-break cycle",
            "Tiếng Việt": "Độ dài pomodoro và chu kỳ nghỉ dài",
        ],
        "Lengths and long-break cycle": [
            "English": "Lengths and long-break cycle",
            "Tiếng Việt": "Độ dài và chu kỳ nghỉ dài",
        ],
        "Last 7 days": ["English": "Last 7 days", "Tiếng Việt": "7 ngày qua"],
        "Selected period": ["English": "Selected period", "Tiếng Việt": "Khoảng đã chọn"],
        "avg session": ["English": "avg session", "Tiếng Việt": "phiên TB"],
        "No focus time yet this week": [
            "English": "No focus time yet this week",
            "Tiếng Việt": "Tuần này chưa có thời gian tập trung",
        ],
        "Sessions before long break": [
            "English": "Sessions before long break",
            "Tiếng Việt": "Số phiên trước nghỉ dài",
        ],
        "Notify when a phase ends": [
            "English": "Notify when a phase ends",
            "Tiếng Việt": "Thông báo khi một giai đoạn kết thúc",
        ],
        "Begin breaks when focus ends": [
            "English": "Begin breaks when focus ends",
            "Tiếng Việt": "Bắt đầu nghỉ khi hết focus",
        ],
        "Begin focus when a break ends": [
            "English": "Begin focus when a break ends",
            "Tiếng Việt": "Bắt đầu focus khi hết nghỉ",
        ],
        "Keep the countdown visible outside Notch": [
            "English": "Keep the countdown visible outside Notch",
            "Tiếng Việt": "Giữ đồng hồ đếm ngược hiện ngoài Notch",
        ],
        "Sign in from Account settings to sync focus ranking.": [
            "English": "Sign in from Account settings to sync focus ranking.",
            "Tiếng Việt": "Đăng nhập trong Account để đồng bộ xếp hạng focus.",
        ],
        "Showing your profile name on the leaderboard.": [
            "English": "Showing your profile name on the leaderboard.",
            "Tiếng Việt": "Hiện tên hồ sơ trên bảng xếp hạng.",
        ],
        "Ranking anonymously on the leaderboard.": [
            "English": "Ranking anonymously on the leaderboard.",
            "Tiếng Việt": "Xếp hạng ẩn danh trên bảng xếp hạng.",
        ],
        "min": ["English": "min", "Tiếng Việt": "phút"],
        "pomo": ["English": "pomo", "Tiếng Việt": "pomo"],
        "Long break every %d focus sessions": [
            "English": "Long break every %d focus sessions",
            "Tiếng Việt": "Nghỉ dài sau mỗi %d phiên tập trung",
        ],
        "Automation": ["English": "Automation", "Tiếng Việt": "Tự động hóa"],
        "Allowed Websites": ["English": "Allowed Websites", "Tiếng Việt": "Trang web được cho phép"],
        "Auto-open on Focus Start": ["English": "Auto-open on Focus Start", "Tiếng Việt": "Tự động mở khi tập trung"],
        "Transition Sound": ["English": "Transition Sound", "Tiếng Việt": "Âm thanh chuyển đổi"],
        "Enable Notifications": ["English": "Enable Notifications", "Tiếng Việt": "Bật thông báo"],
        "Show Focus Timer in Menu Bar": ["English": "Show Focus Timer in Menu Bar", "Tiếng Việt": "Hiện đồng hồ Focus trên thanh menu"],
        "No allowed websites yet.": ["English": "No allowed websites yet.", "Tiếng Việt": "Chưa có trang web được cho phép."],
        "No auto-open URLs yet.": ["English": "No auto-open URLs yet.", "Tiếng Việt": "Chưa có URL tự động mở."],
        "e.g. music.youtube.com": ["English": "e.g. music.youtube.com", "Tiếng Việt": "ví dụ: music.youtube.com"],
        "e.g. notion.so or https://docs.google.com": ["English": "e.g. notion.so or https://docs.google.com", "Tiếng Việt": "ví dụ: notion.so hoặc https://docs.google.com"],
        "domains will never be blocked": ["English": "domains will never be blocked", "Tiếng Việt": "domain sẽ không bao giờ bị chặn"],
        "URLs will open on focus start": ["English": "URLs will open on focus start", "Tiếng Việt": "URL sẽ tự động mở khi bắt đầu tập trung"],
        "%d domains will never be blocked": ["English": "%d domains will never be blocked", "Tiếng Việt": "%d domain sẽ không bao giờ bị chặn"],
        "%d URLs will open on focus start": ["English": "%d URLs will open on focus start", "Tiếng Việt": "%d URL sẽ tự động mở khi bắt đầu tập trung"],
        "Accent": ["English": "Accent", "Tiếng Việt": "Màu nhấn"],
        "Display": ["English": "Display", "Tiếng Việt": "Hiển thị"],
        "Interaction": ["English": "Interaction", "Tiếng Việt": "Tương tác"],
        "Closed Notch Height": ["English": "Closed Notch Height", "Tiếng Việt": "Chiều cao notch đóng"],
        "System": ["English": "System", "Tiếng Việt": "Hệ thống"],
        "Auto-Collapse Delay": ["English": "Auto-Collapse Delay", "Tiếng Việt": "Độ trễ tự đóng"],
        "Connection": ["English": "Connection", "Tiếng Việt": "Kết nối"],
        "Saving...": ["English": "Saving...", "Tiếng Việt": "Đang lưu..."],
        "Model": ["English": "Model", "Tiếng Việt": "Mô hình"],
        "Auto-upload to Google Drive": ["English": "Auto-upload to Google Drive", "Tiếng Việt": "Tự động tải lên Google Drive"],
        "Shelf": ["English": "Shelf", "Tiếng Việt": "Khay lưu trữ"],
        "Manage how dropped items appear, sync, and expire.": ["English": "Manage how dropped items appear, sync, and expire.", "Tiếng Việt": "Quản lý cách nội dung kéo thả hiển thị, đồng bộ và hết hạn."],
        "Behavior": ["English": "Behavior", "Tiếng Việt": "Hành vi"],
        "Storage & Cleanup": ["English": "Storage & Cleanup", "Tiếng Việt": "Lưu trữ & Dọn dẹp"],
        "Item Size": ["English": "Item Size", "Tiếng Việt": "Kích thước mục"],
        "Small": ["English": "Small", "Tiếng Việt": "Nhỏ"],
        "Large": ["English": "Large", "Tiếng Việt": "Lớn"],
        "Show Item Names": ["English": "Show Item Names", "Tiếng Việt": "Hiện tên mục"],
        "Show Google Drive Status Badges": ["English": "Show Google Drive Status Badges", "Tiếng Việt": "Hiện trạng thái Google Drive"],
        "Ignore": ["English": "Ignore", "Tiếng Việt": "Bỏ qua"],
        "Move to Top": ["English": "Move to Top", "Tiếng Việt": "Đưa lên đầu"],
        "Double-click Links": ["English": "Double-click Links", "Tiếng Việt": "Bấm đúp vào liên kết"],
        "Open": ["English": "Open", "Tiếng Việt": "Mở"],
        "Copy URL": ["English": "Copy URL", "Tiếng Việt": "Sao chép URL"],
        "Connected": ["English": "Connected", "Tiếng Việt": "Đã kết nối"],
        "Not Connected": ["English": "Not Connected", "Tiếng Việt": "Chưa kết nối"],
        "Auto-upload New Items": ["English": "Auto-upload New Items", "Tiếng Việt": "Tự tải mục mới lên"],
        "Automatically Upload": ["English": "Automatically Upload", "Tiếng Việt": "Tự động tải lên"],
        "Files Only": ["English": "Files Only", "Tiếng Việt": "Chỉ tệp"],
        "All Items": ["English": "All Items", "Tiếng Việt": "Tất cả mục"],
        "Maximum Items": ["English": "Maximum Items", "Tiếng Việt": "Số mục tối đa"],
        "Remove Items Older Than": ["English": "Remove Items Older Than", "Tiếng Việt": "Xóa mục cũ hơn"],
        "Unlimited": ["English": "Unlimited", "Tiếng Việt": "Không giới hạn"],
        "Never": ["English": "Never", "Tiếng Việt": "Không bao giờ"],
        "1 Day": ["English": "1 Day", "Tiếng Việt": "1 ngày"],
        "7 Days": ["English": "7 Days", "Tiếng Việt": "7 ngày"],
        "30 Days": ["English": "30 Days", "Tiếng Việt": "30 ngày"],
        "Delete Uploaded Google Drive Files During Automatic Cleanup": ["English": "Delete Uploaded Google Drive Files During Automatic Cleanup", "Tiếng Việt": "Xóa tệp Google Drive khi tự dọn Shelf"],
        "Clear Shelf...": ["English": "Clear Shelf...", "Tiếng Việt": "Xóa Shelf..."],
        "Clear Shelf": ["English": "Clear Shelf", "Tiếng Việt": "Xóa Shelf"],
        "%d items stored on Shelf": ["English": "%d items stored on Shelf", "Tiếng Việt": "%d mục trong Shelf"],
        "Apply Retention Policy?": ["English": "Apply Retention Policy?", "Tiếng Việt": "Áp dụng chính sách lưu trữ?"],
        "Apply": ["English": "Apply", "Tiếng Việt": "Áp dụng"],
        "This policy removes %d existing Shelf items.": ["English": "This policy removes %d existing Shelf items.", "Tiếng Việt": "Chính sách này sẽ xóa %d mục đang có trong Shelf."],
        "This policy removes %d Shelf items and deletes %d uploaded Google Drive files.": ["English": "This policy removes %d Shelf items and deletes %d uploaded Google Drive files.", "Tiếng Việt": "Chính sách này sẽ xóa %d mục Shelf và xóa %d tệp đã tải lên Google Drive."],
        "Delete Drive Files Automatically?": ["English": "Delete Drive Files Automatically?", "Tiếng Việt": "Tự động xóa tệp Drive?"],
        "Enable": ["English": "Enable", "Tiếng Việt": "Bật"],
        "Expired or excess Shelf items that were uploaded will also be deleted from Google Drive. This cannot be undone.": ["English": "Expired or excess Shelf items that were uploaded will also be deleted from Google Drive. This cannot be undone.", "Tiếng Việt": "Các mục Shelf hết hạn hoặc vượt giới hạn đã tải lên cũng sẽ bị xóa khỏi Google Drive. Thao tác này không thể hoàn tác."],
        "Clear Shelf?": ["English": "Clear Shelf?", "Tiếng Việt": "Xóa Shelf?"],
        "Remove all %d items from Shelf? This removes local Shelf references and temporary previews.": ["English": "Remove all %d items from Shelf? This removes local Shelf references and temporary previews.", "Tiếng Việt": "Xóa toàn bộ %d mục khỏi Shelf? Thao tác này xóa tham chiếu cục bộ và bản xem trước tạm."],
        "Also delete uploaded files from Google Drive": ["English": "Also delete uploaded files from Google Drive", "Tiếng Việt": "Xóa cả tệp đã tải lên Google Drive"],
        "Delete Google Drive Files?": ["English": "Delete Google Drive Files?", "Tiếng Việt": "Xóa tệp Google Drive?"],
        "Delete Files and Clear Shelf": ["English": "Delete Files and Clear Shelf", "Tiếng Việt": "Xóa tệp và xóa Shelf"],
        "%d uploaded items will be deleted from Google Drive. This cannot be undone.": ["English": "%d uploaded items will be deleted from Google Drive. This cannot be undone.", "Tiếng Việt": "%d mục đã tải lên sẽ bị xóa khỏi Google Drive. Thao tác này không thể hoàn tác."],
        "Delete Uploaded Files from Google Drive?": ["English": "Delete Uploaded Files from Google Drive?", "Tiếng Việt": "Xóa tệp Google Drive đã tải lên?"],
        "This will immediately remove %d items from Shelf and delete %d files from Google Drive. This cannot be undone.": ["English": "This will immediately remove %d items from Shelf and delete %d files from Google Drive. This cannot be undone.", "Tiếng Việt": "Thao tác này sẽ xóa ngay lập tức %d mục trên Shelf và %d tệp trên Google Drive. Không thể hoàn tác."],
        "Delete Files and Enable": ["English": "Delete Files and Enable", "Tiếng Việt": "Xóa tệp và kích hoạt"],
        "Untitled": ["English": "Untitled", "Tiếng Việt": "Chưa đặt tên"],
        "Invalid OAuth callback.": ["English": "Invalid OAuth callback.", "Tiếng Việt": "Phản hồi xác thực OAuth không hợp lệ."],
        "Browser sign-in was cancelled.": ["English": "Browser sign-in was cancelled.", "Tiếng Việt": "Đã hủy đăng nhập trên trình duyệt."],
        "Missing OAuth authorization code.": ["English": "Missing OAuth authorization code.", "Tiếng Việt": "Thiếu mã xác thực OAuth."],
        "Description": ["English": "Description", "Tiếng Việt": "Mô tả"],
        "Recording...": ["English": "Recording...", "Tiếng Việt": "Đang ghi..."],
        "Press Shortcut…": ["English": "Press Shortcut…", "Tiếng Việt": "Nhấn phím tắt…"],
        "Default: %@": ["English": "Default: %@", "Tiếng Việt": "Mặc định: %@"],
        "Rank anonymously": ["English": "Rank anonymously", "Tiếng Việt": "Xếp hạng ẩn danh"],
        "User": ["English": "User", "Tiếng Việt": "Người dùng"],
        "Built-in": ["English": "Built-in", "Tiếng Việt": "Tích hợp"],
        "Exec allows the AI to run arbitrary shell commands on your Mac. This is risky in a voice conversation — the AI may execute commands you don't expect. Only enable this if you fully understand the risks.": ["English": "Exec allows the AI to run arbitrary shell commands on your Mac. This is risky in a voice conversation — the AI may execute commands you don't expect. Only enable this if you fully understand the risks.", "Tiếng Việt": "Lệnh Exec cho phép AI chạy các lệnh terminal bất kỳ trên máy Mac của bạn. Điều này rất rủi ro trong cuộc hội thoại bằng giọng nói — AI có thể chạy các lệnh ngoài ý muốn. Chỉ bật khi bạn đã hiểu rõ rủi ro."],
        "Open System Settings": ["English": "Open System Settings", "Tiếng Việt": "Mở Cài đặt Hệ thống"],
        "%@ requires Full Disk Access to read local data. Please add Notch to the Full Disk Access list in System Settings > Privacy & Security.": ["English": "%@ requires Full Disk Access to read local data. Please add Notch to the Full Disk Access list in System Settings > Privacy & Security.", "Tiếng Việt": "%@ cần quyền Truy cập Toàn bộ Ổ đĩa để đọc dữ liệu cục bộ. Vui lòng thêm Notch vào danh sách Truy cập Toàn bộ Ổ đĩa trong Cài đặt Hệ thống > Quyền riêng tư & Bảo mật."],
        "Launch At Login": ["English": "Launch At Login", "Tiếng Việt": "Khởi động cùng máy"],
        // MARK: TOEIC Study
        "TOEIC": ["English": "TOEIC", "Tiếng Việt": "TOEIC"],
        "TOEIC Study": ["English": "TOEIC Study", "Tiếng Việt": "Học TOEIC"],
        "Native vocab + Part 5 practice": [
            "English": "Native vocab + Part 5 practice",
            "Tiếng Việt": "Từ vựng native + luyện Part 5",
        ],
        "Offline pack + AI via localhost OpenAI API": [
            "English": "Offline pack + AI via localhost OpenAI API",
            "Tiếng Việt": "Gói offline + AI qua API OpenAI localhost",
        ],
        "Bundled Study4 vocab · flashcards + quiz": [
            "English": "Bundled Study4 vocab · flashcards + quiz",
            "Tiếng Việt": "Từ vựng Study4 nhúng app · flashcard + quiz",
        ],
        "Vocab bank: %d words": [
            "English": "Vocab bank: %d words",
            "Tiếng Việt": "Kho từ: %d từ",
        ],
        "Bundled vocab · offline": [
            "English": "Bundled vocab · offline",
            "Tiếng Việt": "Từ vựng nhúng · offline",
        ],
        "Vocab %d · Known %d · Today %d": [
            "English": "Vocab %d · Known %d · Today %d",
            "Tiếng Việt": "Từ %d · Thuộc %d · Hôm nay %d",
        ],
        "Study during Focus": [
            "English": "Study during Focus",
            "Tiếng Việt": "Học khi Focus",
        ],
        "Opens automatically while Focus is running": [
            "English": "Opens automatically while Focus is running",
            "Tiếng Việt": "Tự mở khi Focus đang chạy",
        ],
        "Start Focus → study window opens. Break / pause → closes.": [
            "English": "Start Focus → study window opens. Break / pause → closes.",
            "Tiếng Việt": "Bắt đầu Focus → mở cửa sổ học. Nghỉ / tạm dừng → đóng.",
        ],
        "Pronounce": [
            "English": "Pronounce",
            "Tiếng Việt": "Phát âm",
        ],
        "Progress": [
            "English": "Progress",
            "Tiếng Việt": "Tiến độ",
        ],
        "Vocab flashcards and Part 5 style practice": [
            "English": "Vocab flashcards and Part 5 style practice",
            "Tiếng Việt": "Flashcard từ vựng và luyện dạng Part 5",
        ],
        "Flashcards": ["English": "Flashcards", "Tiếng Việt": "Flashcard"],
        "Quiz": ["English": "Quiz", "Tiếng Việt": "Trắc nghiệm"],
        "Known": ["English": "Known", "Tiếng Việt": "Đã thuộc"],
        "Shuffle": ["English": "Shuffle", "Tiếng Việt": "Xáo trộn"],
        "Built-in TOEIC pack · offline": [
            "English": "Built-in TOEIC pack · offline",
            "Tiếng Việt": "Gói TOEIC có sẵn · offline",
        ],
        "Tap card to flip": ["English": "Tap card to flip", "Tiếng Việt": "Bấm thẻ để lật"],
        "Again": ["English": "Again", "Tiếng Việt": "Học lại"],
        "Know": ["English": "Know", "Tiếng Việt": "Đã biết"],
        "Next question": ["English": "Next question", "Tiếng Việt": "Câu tiếp"],
        "No cards": ["English": "No cards", "Tiếng Việt": "Không có thẻ"],
        "No questions": ["English": "No questions", "Tiếng Việt": "Không có câu hỏi"],
        "Known %d · Today %d · Quiz %d%%": [
            "English": "Known %d · Today %d · Quiz %d%%",
            "Tiếng Việt": "Thuộc %d · Hôm nay %d · Quiz %d%%",
        ],
        "AI Quiz": ["English": "AI Quiz", "Tiếng Việt": "Quiz AI"],
        "New quiz set": ["English": "New quiz set", "Tiếng Việt": "Bộ quiz mới"],
        "Quiz ready: %d": [
            "English": "Quiz ready: %d",
            "Tiếng Việt": "Quiz sẵn sàng: %d",
        ],
        "Prebuilt quiz · offline": [
            "English": "Prebuilt quiz · offline",
            "Tiếng Việt": "Quiz có sẵn · offline",
        ],
        "SRS quiz · spaced + interleaved": [
            "English": "SRS quiz · spaced + interleaved",
            "Tiếng Việt": "Quiz SRS · giãn cách + xen kẽ",
        ],
        "Due": ["English": "Due", "Tiếng Việt": "Tới hạn"],
        "New": ["English": "New", "Tiếng Việt": "Mới"],
        "AI Vocab": ["English": "AI Vocab", "Tiếng Việt": "Từ vựng AI"],
        "Word bank + AI stems": [
            "English": "Word bank + AI stems",
            "Tiếng Việt": "Kho từ + câu AI",
        ],
        "Word bank · offline": [
            "English": "Word bank · offline",
            "Tiếng Việt": "Kho từ · offline",
        ],
        "Drawing from word bank…": [
            "English": "Drawing from word bank…",
            "Tiếng Việt": "Đang bốc từ kho…",
        ],
        "Building quiz from bank…": [
            "English": "Building quiz from bank…",
            "Tiếng Việt": "Đang dựng quiz từ kho…",
        ],
        "Preparing examples…": [
            "English": "Preparing examples…",
            "Tiếng Việt": "Đang chuẩn bị câu ví dụ…",
        ],
        "Refreshing examples…": [
            "English": "Refreshing examples…",
            "Tiếng Việt": "Đang làm mới ví dụ…",
        ],
        "Word bank is empty": [
            "English": "Word bank is empty",
            "Tiếng Việt": "Kho từ trống",
        ],
        "AI returned no questions": [
            "English": "AI returned no questions",
            "Tiếng Việt": "AI không trả câu hỏi",
        ],
        "Quiz from bank: %d words": [
            "English": "Quiz from bank: %d words",
            "Tiếng Việt": "Quiz từ kho: %d từ",
        ],
        "Study set from bank: %d words": [
            "English": "Study set from bank: %d words",
            "Tiếng Việt": "Bộ học từ kho: %d từ",
        ],
        "AI explain unavailable · offline note shown": [
            "English": "AI explain unavailable · offline note shown",
            "Tiếng Việt": "Không giải thích AI · dùng ghi chú offline",
        ],
        "Bank %d words · mastery %d": [
            "English": "Bank %d words · mastery %d",
            "Tiếng Việt": "Kho %d từ · mastery %d",
        ],
        "Bank %d · mastery %d · Q %d": [
            "English": "Bank %d · mastery %d · Q %d",
            "Tiếng Việt": "Kho %d · mastery %d · câu %d",
        ],
        "words": ["English": "words", "Tiếng Việt": "từ"],
        "Reload bank + progress": [
            "English": "Reload bank + progress",
            "Tiếng Việt": "Tải lại kho + tiến trình",
        ],

        // MARK: Shortcuts (QuickKey)
        "Shortcuts": ["English": "Shortcuts", "Tiếng Việt": "Phím tắt"],
        "Map spare keys to any app shortcut": [
            "English": "Map spare keys or mouse side buttons to any app shortcut",
            "Tiếng Việt": "Gán phím thừa hoặc nút bên chuột thành phím tắt của app",
        ],
        "Accessibility required": [
            "English": "Accessibility required",
            "Tiếng Việt": "Cần quyền Trợ năng",
        ],
        "Needed to read and send key events": [
            "English": "Needed to read and send key / mouse events",
            "Tiếng Việt": "Cần để đọc và gửi sự kiện phím / chuột",
        ],
        "Open Settings": ["English": "Open Settings", "Tiếng Việt": "Mở Cài đặt"],
        "Grant": ["English": "Grant", "Tiếng Việt": "Cấp quyền"],
        "Engine": ["English": "Engine", "Tiếng Việt": "Công cụ"],
        "Enable remapper": ["English": "Enable remapper", "Tiếng Việt": "Bật remap phím"],
        "active": ["English": "active", "Tiếng Việt": "đang bật"],
        "Keybindings": ["English": "Keybindings", "Tiếng Việt": "Phím gán"],
        "Key → Send": ["English": "Key → Send", "Tiếng Việt": "Phím → Gửi"],
        "No shortcuts yet": ["English": "No shortcuts yet", "Tiếng Việt": "Chưa có phím tắt"],
        "Add shortcut": ["English": "Add shortcut", "Tiếng Việt": "Thêm phím tắt"],
        "New Shortcut": ["English": "New Shortcut", "Tiếng Việt": "Phím tắt mới"],
        "Edit Shortcut": ["English": "Edit Shortcut", "Tiếng Việt": "Sửa phím tắt"],
        "Shortcut": ["English": "Shortcut", "Tiếng Việt": "Phím tắt"],
        "Key": ["English": "Key", "Tiếng Việt": "Phím"],
        "Send": ["English": "Send", "Tiếng Việt": "Gửi"],
        "When": ["English": "When", "Tiếng Việt": "Khi"],
        "Choose app…": ["English": "Choose app…", "Tiếng Việt": "Chọn ứng dụng…"],
        "Choose App": ["English": "Choose App", "Tiếng Việt": "Chọn ứng dụng"],
        "OK": ["English": "OK", "Tiếng Việt": "OK"],
        "key · chord · x2 · x3": [
            "English": "key · chord · x2 · x3",
            "Tiếng Việt": "phím · tổ hợp · x2 · x3",
        ],
        "key · mouse4 · mouse5 · x2": [
            "English": "key · mouse4 · mouse5 · x2",
            "Tiếng Việt": "phím · mouse4 · mouse5 · x2",
        ],
        "1 shortcut → 1 shortcut. Multi-tap while recording: ×2 / ×3.": [
            "English": "1 shortcut → 1 shortcut. Multi-tap while recording: ×2 / ×3.",
            "Tiếng Việt": "1 phím tắt → 1 phím tắt. Bấm nhiều lần khi ghi: ×2 / ×3.",
        ],
        "Key, mouse side buttons (Mouse 4/5), or Middle. Multi-tap while recording: ×2 / ×3.": [
            "English": "Key, mouse side buttons (Mouse 4/5), or Middle. Multi-tap while recording: ×2 / ×3.",
            "Tiếng Việt": "Phím, nút bên chuột (Mouse 4/5), hoặc Middle. Bấm nhiều lần khi ghi: ×2 / ×3.",
        ],
        "Press · double · triple…": [
            "English": "Press · double · triple…",
            "Tiếng Việt": "Bấm · double · triple…",
        ],
        "Press key or mouse side…": [
            "English": "Press key or mouse side…",
            "Tiếng Việt": "Nhấn phím hoặc nút bên chuột…",
        ],
        "Press keys…": ["English": "Press keys…", "Tiếng Việt": "Nhấn phím…"],
        "Stop (Esc)": ["English": "Stop (Esc)", "Tiếng Việt": "Dừng (Esc)"],
        "Record key or mouse button (multi-tap = ×2 / ×3)": [
            "English": "Record key or mouse button (multi-tap = ×2 / ×3)",
            "Tiếng Việt": "Ghi phím hoặc nút chuột (bấm nhiều = ×2 / ×3)",
        ],
        "Record key (multi-tap = ×2 / ×3)": [
            "English": "Record key (multi-tap = ×2 / ×3)",
            "Tiếng Việt": "Ghi phím (bấm nhiều = ×2 / ×3)",
        ],
        "Record keys": ["English": "Record keys", "Tiếng Việt": "Ghi phím"],
        "Empty": ["English": "Empty", "Tiếng Việt": "Trống"],
        "Missing key": ["English": "Missing key", "Tiếng Việt": "Thiếu phím"],
        "Only one main key": ["English": "Only one main key", "Tiếng Việt": "Chỉ một phím chính"],
        "Empty keybinding": ["English": "Empty keybinding", "Tiếng Việt": "Phím tắt trống"],
        "Unknown": ["English": "Unknown", "Tiếng Việt": "Không rõ"],

        "No agent results yet": ["English": "No agent results yet", "Tiếng Việt": "Chưa có kết quả từ agent"],
        "Items pushed by agents will appear here.": ["English": "Items pushed by agents will appear here.", "Tiếng Việt": "Các mục được gửi từ agent sẽ xuất hiện tại đây."],
        "Copy all visible items": ["English": "Copy all visible items", "Tiếng Việt": "Sao chép tất cả mục đang hiện"],
        "Close results": ["English": "Close results", "Tiếng Việt": "Đóng kết quả"],
        "Show item %d": ["English": "Show item %d", "Tiếng Việt": "Hiển thị mục %d"],
        "Show previous results": ["English": "Show previous results", "Tiếng Việt": "Hiển thị kết quả trước"],
        "Open file": ["English": "Open file", "Tiếng Việt": "Mở tệp"],
        "Reveal in Finder": ["English": "Reveal in Finder", "Tiếng Việt": "Hiện trong Finder"],
        "Open link": ["English": "Open link", "Tiếng Việt": "Mở liên kết"],
        "Copy link": ["English": "Copy link", "Tiếng Việt": "Sao chép liên kết"],
        "Open image": ["English": "Open image", "Tiếng Việt": "Mở ảnh"],
        "Copy image": ["English": "Copy image", "Tiếng Việt": "Sao chép ảnh"],
        "Copied": ["English": "Copied", "Tiếng Việt": "Đã sao chép"],
        "NOW PLAYING": ["English": "NOW PLAYING", "Tiếng Việt": "ĐANG PHÁT"],
        "Stop": ["English": "Stop", "Tiếng Việt": "Dừng"],
        "Replay": ["English": "Replay", "Tiếng Việt": "Nghe lại"],
        "Copy": ["English": "Copy", "Tiếng Việt": "Sao chép"],
        "See more %d results…": ["English": "See more %d results…", "Tiếng Việt": "Xem thêm %d kết quả…"],
        "⚠️ Enable Shell Access?": ["English": "⚠️ Enable Shell Access?", "Tiếng Việt": "⚠️ Bật quyền truy cập Terminal?"],
        "🔒 Full Disk Access Required": ["English": "🔒 Full Disk Access Required", "Tiếng Việt": "🔒 Yêu cầu quyền truy cập ổ đĩa đầy đủ"],
        "This tool": ["English": "This tool", "Tiếng Việt": "Công cụ này"],
        "Reveal": ["English": "Reveal", "Tiếng Việt": "Hiện"],
        "Couldn't change Launch At Login": ["English": "Couldn't change Launch At Login", "Tiếng Việt": "Không thể thay đổi cài đặt Khởi động cùng hệ thống"],
        "Searching web…": ["English": "Searching web…", "Tiếng Việt": "Đang tìm kiếm web…"],
        "Reading file…": ["English": "Reading file…", "Tiếng Việt": "Đang đọc tệp…"],
        "Checking calendar…": ["English": "Checking calendar…", "Tiếng Việt": "Đang kiểm tra lịch…"],
        "Listing files…": ["English": "Listing files…", "Tiếng Việt": "Đang liệt kê tệp…"],
        "Using clipboard…": ["English": "Using clipboard…", "Tiếng Việt": "Đang dùng bảng tạm…"],
        "Controlling app…": ["English": "Controlling app…", "Tiếng Việt": "Đang điều khiển ứng dụng…"],
        "Controlling media…": ["English": "Controlling media…", "Tiếng Việt": "Đang điều khiển nhạc…"],
        "Controlling timer…": ["English": "Controlling timer…", "Tiếng Việt": "Đang điều khiển bộ hẹn giờ…"],
        "Using browser…": ["English": "Using browser…", "Tiếng Việt": "Đang dùng trình duyệt…"],
        "Searching files…": ["English": "Searching files…", "Tiếng Việt": "Đang tìm tệp…"],
        "Using memory…": ["English": "Using memory…", "Tiếng Việt": "Đang truy xuất bộ nhớ…"],
        "Running command…": ["English": "Running command…", "Tiếng Việt": "Đang chạy lệnh…"],
        "Skill writer pending approval…": ["English": "Skill writer pending approval…", "Tiếng Việt": "Đang chờ duyệt tạo kỹ năng…"],
        "Searched: %@": ["English": "Searched: %@", "Tiếng Việt": "Đã tìm: %@"],
        "Found 1 web result": ["English": "Found 1 web result", "Tiếng Việt": "Tìm thấy 1 kết quả web"],
        "Found %d web results": ["English": "Found %d web results", "Tiếng Việt": "Tìm thấy %d kết quả web"],
        "Web search completed": ["English": "Web search completed", "Tiếng Việt": "Tìm kiếm web hoàn tất"],
        "Read %@": ["English": "Read %@", "Tiếng Việt": "Đã đọc %@"],
        "Read %d bytes": ["English": "Read %d bytes", "Tiếng Việt": "Đã đọc %d byte"],
        "Read file": ["English": "Read file", "Tiếng Việt": "Đọc tệp"],
        "Listed 1 item in %@": ["English": "Listed 1 item in %@", "Tiếng Việt": "Đã liệt kê 1 mục trong %@"],
        "Listed %d items in %@": ["English": "Listed %d items in %@", "Tiếng Việt": "Đã liệt kê %d mục trong %@"],
        "Listed %@": ["English": "Listed %@", "Tiếng Việt": "Đã liệt kê %@"],
        "Listed 1 item": ["English": "Listed 1 item", "Tiếng Việt": "Đã liệt kê 1 mục"],
        "Listed %d items": ["English": "Listed %d items", "Tiếng Việt": "Đã liệt kê %d mục"],
        "Listed files": ["English": "Listed files", "Tiếng Việt": "Liệt kê tệp"],
        "Read clipboard (%d chars)": ["English": "Read clipboard (%d chars)", "Tiếng Việt": "Đã đọc bảng tạm (%d ký tự)"],
        "Clipboard is empty": ["English": "Clipboard is empty", "Tiếng Việt": "Bảng tạm trống"],
        "Copied text": ["English": "Copied text", "Tiếng Việt": "Đã sao chép văn bản"],
        "Copied files": ["English": "Copied files", "Tiếng Việt": "Đã sao chép tệp"],
        "Clipboard action completed": ["English": "Clipboard action completed", "Tiếng Việt": "Thao tác bảng tạm hoàn tất"],
        "Opened %@": ["English": "Opened %@", "Tiếng Việt": "Đã mở %@"],
        "Quit %@": ["English": "Quit %@", "Tiếng Việt": "Đã thoát %@"],
        "%@ is running": ["English": "%@ is running", "Tiếng Việt": "%@ đang chạy"],
        "%@ is not running": ["English": "%@ is not running", "Tiếng Việt": "%@ không chạy"],
        "Checked %@": ["English": "Checked %@", "Tiếng Việt": "Đã kiểm tra %@"],
        "App action completed": ["English": "App action completed", "Tiếng Việt": "Thao tác ứng dụng hoàn tất"],
        "Now playing: %@": ["English": "Now playing: %@", "Tiếng Việt": "Đang phát: %@"],
        "Checked media status": ["English": "Checked media status", "Tiếng Việt": "Đã kiểm tra trạng thái nhạc"],
        "Volume is %d%%": ["English": "Volume is %d%%", "Tiếng Việt": "Âm lượng ở mức %d%%"],
        "Checked volume": ["English": "Checked volume", "Tiếng Việt": "Đã kiểm tra âm lượng"],
        "Set volume to %d%%": ["English": "Set volume to %d%%", "Tiếng Việt": "Đã đặt âm lượng thành %d%%"],
        "Set volume": ["English": "Set volume", "Tiếng Việt": "Đặt âm lượng"],
        "Started playback": ["English": "Started playback", "Tiếng Việt": "Đã bắt đầu phát"],
        "Paused playback": ["English": "Paused playback", "Tiếng Việt": "Đã tạm dừng phát"],
        "Toggled playback": ["English": "Toggled playback", "Tiếng Việt": "Đã chuyển đổi phát nhạc"],
        "Skipped to next track": ["English": "Skipped to next track", "Tiếng Việt": "Đã bỏ qua tới bài tiếp theo"],
        "Returned to previous track": ["English": "Returned to previous track", "Tiếng Việt": "Đã quay lại bài trước"],
        "Skipped forward %@s": ["English": "Skipped forward %@s", "Tiếng Việt": "Đã tua nhanh %@ giây"],
        "Skipped back %@s": ["English": "Skipped back %@s", "Tiếng Việt": "Đã tua lùi %@ giây"],
        "Media action completed": ["English": "Media action completed", "Tiếng Việt": "Thao tác nhạc hoàn tất"],
        "Checked focus timer": ["English": "Checked focus timer", "Tiếng Việt": "Đã kiểm tra bộ hẹn giờ tập trung"],
        "Started focus timer": ["English": "Started focus timer", "Tiếng Việt": "Đã bắt đầu bộ hẹn giờ tập trung"],
        "Paused focus timer": ["English": "Paused focus timer", "Tiếng Việt": "Đã tạm dừng bộ hẹn giờ tập trung"],
        "Resumed focus timer": ["English": "Resumed focus timer", "Tiếng Việt": "Đã tiếp tục bộ hẹn giờ tập trung"],
        "Reset focus timer": ["English": "Reset focus timer", "Tiếng Việt": "Đã đặt lại bộ hẹn giờ tập trung"],
        "Skipped focus phase": ["English": "Skipped focus phase", "Tiếng Việt": "Đã bỏ qua giai đoạn tập trung"],
        "Skill write approval needed": ["English": "Skill write approval needed", "Tiếng Việt": "Cần phê duyệt tạo kỹ năng"],
        "Allow Save": ["English": "Allow Save", "Tiếng Việt": "Cho phép lưu"],
        "Delete skill?": ["English": "Delete skill?", "Tiếng Việt": "Xóa kỹ năng?"],
        "Delete \"%@\" from Notch? You can recreate it anytime.": [
            "English": "Delete \"%@\" from Notch? You can recreate it anytime.",
            "Tiếng Việt": "Xóa \"%@\" khỏi Notch? Bạn có thể tạo lại bất cứ lúc nào."
        ],
        "Deleted skill \"%@\".": ["English": "Deleted skill \"%@\".", "Tiếng Việt": "Đã xóa kỹ năng \"%@\"."],
        "Skill deletion failed.": ["English": "Skill deletion failed.", "Tiếng Việt": "Xóa kỹ năng thất bại."],
        "Skill saved.": ["English": "Skill saved.", "Tiếng Việt": "Đã lưu kỹ năng."],
        "Duplicated skill.": ["English": "Duplicated skill.", "Tiếng Việt": "Đã nhân bản kỹ năng."],
        "Couldn't duplicate skill.": ["English": "Couldn't duplicate skill.", "Tiếng Việt": "Không thể nhân bản kỹ năng."],
        "Open Link": ["English": "Open Link", "Tiếng Việt": "Mở liên kết"],
        "Copy Text": ["English": "Copy Text", "Tiếng Việt": "Sao chép văn bản"],
        "Show in Finder": ["English": "Show in Finder", "Tiếng Việt": "Hiển thị trong Finder"],
        "Open Selected": ["English": "Open Selected", "Tiếng Việt": "Mở mục đã chọn"],
        "Copy Selected": ["English": "Copy Selected", "Tiếng Việt": "Sao chép mục đã chọn"],
        "Upload to Google Drive": ["English": "Upload to Google Drive", "Tiếng Việt": "Tải lên Google Drive"],
        "Share": ["English": "Share", "Tiếng Việt": "Chia sẻ"],
        "Open in Google Drive": ["English": "Open in Google Drive", "Tiếng Việt": "Mở trong Google Drive"],
        "Sync changes to Drive": ["English": "Sync changes to Drive", "Tiếng Việt": "Đồng bộ thay đổi lên Drive"],
        "Link Google Drive": ["English": "Link Google Drive", "Tiếng Việt": "Kết nối Google Drive"],
        "Remove from Shelf": ["English": "Remove from Shelf", "Tiếng Việt": "Xóa khỏi Shelf"],
        "Remove Selected": ["English": "Remove Selected", "Tiếng Việt": "Xóa mục đã chọn"],
        "Local file missing; Drive copy may still exist": [
            "English": "Local file missing; Drive copy may still exist",
            "Tiếng Việt": "Tệp cục bộ bị thiếu; bản sao Drive có thể vẫn tồn tại"
        ],
        "Local file missing": [
            "English": "Local file missing",
            "Tiếng Việt": "Tệp cục bộ bị thiếu"
        ],
    ]

    static func get(_ key: String) -> String {
        let lang = UserDefaults.standard.string(forKey: "app_language") ?? "English"
        return get(key, lang: lang)
    }

    static func get(_ key: String, lang: String) -> String {
        return dict[key]?[lang] ?? key
    }
}

// MARK: - Global Settings View
