import Foundation

// MARK: - Localization Support

struct Localization {
    private static let dict: [String: [String: String]] = [
        "General Settings": ["English": "General Settings", "Tiếng Việt": "Cài đặt chung"],
        "General": ["English": "General", "Tiếng Việt": "Chung"],
        "API Keys": ["English": "API Keys", "Tiếng Việt": "API Key"],
        "Language": ["English": "Language", "Tiếng Việt": "Ngôn ngữ"],
        "Launch at Login": ["English": "Launch at Login", "Tiếng Việt": "Khởi động cùng máy"],
        "Hover to Open": ["English": "Hover to Open", "Tiếng Việt": "Mở khi rê chuột"],
        "Hover Open Delay": ["English": "Hover Open Delay", "Tiếng Việt": "Độ trễ mở khi rê chuột"],
        "Adjust how long the pointer must stay over the notch before it opens.": ["English": "Adjust how long the pointer must stay over the notch before it opens.", "Tiếng Việt": "Chỉnh thời gian con trỏ cần đứng trên notch trước khi nó mở ra."],
        "Accent Color": ["English": "Accent Color", "Tiếng Việt": "Màu nhấn"],
        "Choose the shared accent used for Talk controls and settings buttons.": ["English": "Choose the shared accent used for Talk controls and settings buttons.", "Tiếng Việt": "Chọn màu nhấn chung cho các nút trong Talk và phần cài đặt."],
        "Ocean": ["English": "Ocean", "Tiếng Việt": "Biển xanh"],
        "Mint": ["English": "Mint", "Tiếng Việt": "Bạc hà"],
        "Gold": ["English": "Gold", "Tiếng Việt": "Vàng"],
        "Coral": ["English": "Coral", "Tiếng Việt": "San hô"],
        "Rose": ["English": "Rose", "Tiếng Việt": "Hồng"],
        "Cycle": ["English": "Cycle", "Tiếng Việt": "Chu kỳ"],
        "Version": ["English": "Version", "Tiếng Việt": "Phiên bản"],
        "Focus": ["English": "Focus", "Tiếng Việt": "Tập trung"],
        "Focus Sound": ["English": "Focus Sound", "Tiếng Việt": "Âm đổi focus"],
        "Short": ["English": "Short", "Tiếng Việt": "Nghỉ ngắn"],
        "Long": ["English": "Long", "Tiếng Việt": "Nghỉ dài"],
        "Blocked Websites": ["English": "Blocked Websites", "Tiếng Việt": "Trang web bị chặn"],
        "Enter one domain per line. Example: youtube.com": [
            "English": "Enter one domain per line. Example: youtube.com",
            "Tiếng Việt": "Nhập mỗi domain trên một dòng. Ví dụ: youtube.com",
        ],
        "%d domains synced to Chrome extension": [
            "English": "%d domains synced to Chrome extension",
            "Tiếng Việt": "%d domain đã đồng bộ sang extension Chrome",
        ],
        "Chrome reads this list live while focus is running.": [
            "English": "Chrome reads this list live while focus is running.",
            "Tiếng Việt": "Chrome đọc danh sách này trực tiếp khi focus đang chạy.",
        ],
        "Round": ["English": "Round", "Tiếng Việt": "Vòng"],
        "Time": ["English": "Time", "Tiếng Việt": "Thời gian"],
        "Stats": ["English": "Stats", "Tiếng Việt": "Thống kê"],
        "Settings": ["English": "Settings", "Tiếng Việt": "Cài đặt"],
        "Last 7 Days": ["English": "Last 7 Days", "Tiếng Việt": "7 ngày qua"],
        "Focus on": ["English": "Focus on", "Tiếng Việt": "Tập trung ngày"],
        "Break": ["English": "Break", "Tiếng Việt": "Giải lao"],
        "Pause": ["English": "Pause", "Tiếng Việt": "Tạm dừng"],
        "Resume": ["English": "Resume", "Tiếng Việt": "Tiếp tục"],
        "Start Focus": ["English": "Start Focus", "Tiếng Việt": "Bắt đầu tập trung"],
        "Start": ["English": "Start", "Tiếng Việt": "Bắt đầu"],
        "Reset": ["English": "Reset", "Tiếng Việt": "Đặt lại"],
        "Skip": ["English": "Skip", "Tiếng Việt": "Bỏ qua"],
        "Next": ["English": "Next", "Tiếng Việt": "Tiếp theo"],
        "Auto Start Breaks": ["English": "Auto Start Breaks", "Tiếng Việt": "Tự chạy khi nghỉ"],
        "Auto Start Pomo": ["English": "Auto Start Pomo", "Tiếng Việt": "Tự chạy Pomo"],
        "Auto Breaks": ["English": "Auto Breaks", "Tiếng Việt": "Tự bật nghỉ"],
        "Auto Pomo": ["English": "Auto Pomo", "Tiếng Việt": "Tự bật Pomo"],
        "Focus Session": ["English": "Focus Session", "Tiếng Việt": "Đang tập trung"],
        "Short Break": ["English": "Short Break", "Tiếng Việt": "Giải lao ngắn"],
        "Long Break": ["English": "Long Break", "Tiếng Việt": "Giải lao dài"],
        "Pomodoro": ["English": "Pomodoro", "Tiếng Việt": "Tập trung"],
        "Mon": ["English": "Mon", "Tiếng Việt": "Th 2"],
        "Tue": ["English": "Tue", "Tiếng Việt": "Th 3"],
        "Wed": ["English": "Wed", "Tiếng Việt": "Th 4"],
        "Thu": ["English": "Thu", "Tiếng Việt": "Th 5"],
        "Fri": ["English": "Fri", "Tiếng Việt": "Th 6"],
        "Sat": ["English": "Sat", "Tiếng Việt": "Th 7"],
        "Sun": ["English": "Sun", "Tiếng Việt": "CN"],
        "Back": ["English": "Back", "Tiếng Việt": "Quay lại"],
        "Save": ["English": "Save", "Tiếng Việt": "Lưu"],
        "Profile": ["English": "Profile", "Tiếng Việt": "Hồ sơ"],
        "Tools": ["English": "Tools", "Tiếng Việt": "Công cụ"],
        "Skills": ["English": "Skills", "Tiếng Việt": "Kỹ năng"],
        "Common": ["English": "General", "Tiếng Việt": "Chung"],
        "Push to Talk hint": [
            "English": "Used only in Push to Talk mode while Gemini Live is connected. Shortcuts must include at least one modifier key.",
            "Tiếng Việt": "Chỉ dùng ở chế độ Nhấn để nói khi Gemini Live đang kết nối. Phím tắt cần có ít nhất một phím bổ trợ (⌘, ⌥, ⌃ hoặc ⇧).",
        ],
        "System Prompt": ["English": "System Prompt", "Tiếng Việt": "Lời nhắc hệ thống"],
        "New Agent": ["English": "New Agent", "Tiếng Việt": "Agent mới"],
        "Delete Agent": ["English": "Delete Agent", "Tiếng Việt": "Xóa Agent"],
        "Voice": ["English": "Voice", "Tiếng Việt": "Giọng nói"],
        "Thinking": ["English": "Thinking", "Tiếng Việt": "Suy nghĩ"],
        "Agent": ["English": "Agent", "Tiếng Việt": "Trợ lý"],
        "Manage keys": ["English": "Manage keys", "Tiếng Việt": "Quản lý Key"],
        "Online": ["English": "Online", "Tiếng Việt": "Đang online"],
        "Ready": ["English": "Ready", "Tiếng Việt": "Sẵn sàng"],
        "Readiness": ["English": "Readiness", "Tiếng Việt": "Độ sẵn sàng"],
        "Selected agent": ["English": "Selected agent", "Tiếng Việt": "Trợ lý đang chọn"],
        "Ready to start a live conversation.": ["English": "Ready to start a live conversation.", "Tiếng Việt": "Sẵn sàng bắt đầu trò chuyện trực tiếp."],
        "is ready": ["English": "is ready", "Tiếng Việt": "đã sẵn sàng"],
        "Screen": ["English": "Screen", "Tiếng Việt": "Màn hình"],
        "Start Talking": ["English": "Start Talking", "Tiếng Việt": "Bắt đầu nói"],
        "Voice-first Talk surface": ["English": "Voice-first Talk surface", "Tiếng Việt": "Giao diện ưu tiên giọng nói"],
        "Connect": ["English": "Connect", "Tiếng Việt": "Kết nối"],
        "Disconnect": ["English": "Disconnect", "Tiếng Việt": "Ngắt kết nối"],
        "End": ["English": "End", "Tiếng Việt": "Kết thúc"],
        "Open Mic": ["English": "Open Mic", "Tiếng Việt": "Mic"],
        "Push to Talk": ["English": "Push to Talk", "Tiếng Việt": "Nhấn để nói"],
        "Push to Talk key": ["English": "Push to Talk key", "Tiếng Việt": "Phím bấm để nói"],
        "Hold": ["English": "Hold", "Tiếng Việt": "Giữ"],
        "Listening": ["English": "Listening", "Tiếng Việt": "Đang nghe"],
        "Mic": ["English": "Mic", "Tiếng Việt": "Mic"],
        "Muted": ["English": "Muted", "Tiếng Việt": "Tắt tiếng"],
        "Subs": ["English": "Subs", "Tiếng Việt": "Phụ đề"],
        "Subs Off": ["English": "Subs Off", "Tiếng Việt": "Phụ đề Tắt"],
        "Subs Auto": ["English": "Subs Auto", "Tiếng Việt": "Phụ đề Tự ẩn"],
        "Subs Pin": ["English": "Subs Pin", "Tiếng Việt": "Phụ đề Ghim"],
        "Type": ["English": "Type", "Tiếng Việt": "Nhập"],
        "Hide": ["English": "Hide", "Tiếng Việt": "Ẩn"],
        "Pin": ["English": "Pin", "Tiếng Việt": "Ghim"],
        "Context": ["English": "Context", "Tiếng Việt": "Ngữ cảnh"],
        "Gemini is listening...": ["English": "Gemini is listening...", "Tiếng Việt": "Đang nghe..."],
        "Thinking...": ["English": "Thinking...", "Tiếng Việt": "Đang nghĩ..."],
        "Delete Agent?": ["English": "Delete Agent?", "Tiếng Việt": "Xóa trợ lý này?"],
        "Cancel": ["English": "Cancel", "Tiếng Việt": "Hủy"],
        "Delete": ["English": "Delete", "Tiếng Việt": "Xóa"],
        "Back to Home": ["English": "Back to Home", "Tiếng Việt": "Trang chủ"],
        "Nothing Playing": ["English": "Nothing Playing", "Tiếng Việt": "Không có nội dung"],
        "System Media": ["English": "System Media", "Tiếng Việt": "Hệ thống"],
        "Done": ["English": "Done", "Tiếng Việt": "Xong"],
        "Gemini Live needs a Gemini API key.": ["English": "Gemini Live needs a Gemini API key.", "Tiếng Việt": "Gemini Live cần một API Key."],
        "Keys are not entered in the notch. Use the menu bar or Manage keys below.": ["English": "Keys are not entered in the notch. Use the menu bar or Manage keys below.", "Tiếng Việt": "Key không thể nhập tại Notch. Hãy dùng Menu Bar hoặc nút Quản lý Key bên dưới."],
        "Approve Command": ["English": "Approve Command", "Tiếng Việt": "Phê duyệt lệnh"],
        "Deny": ["English": "Deny", "Tiếng Việt": "Từ chối"],
        "Gemini API Key": ["English": "Gemini API Key", "Tiếng Việt": "Gemini API Key"],
        "Saved": ["English": "Saved", "Tiếng Việt": "Đã lưu"],
        "Save API key to local": ["English": "Save API key to local", "Tiếng Việt": "Lưu API Key vào máy"],
        "Allow Once": ["English": "Allow Once", "Tiếng Việt": "Cho phép 1 lần"],
        "Once": ["English": "Once", "Tiếng Việt": "1 lần"],
        "Always Exact": ["English": "Always Exact", "Tiếng Việt": "Luôn lệnh này"],
        "Exact": ["English": "Exact", "Tiếng Việt": "Lệnh này"],
        "Always": ["English": "Always", "Tiếng Việt": "Luôn"],
        "Enable All": ["English": "Enable All", "Tiếng Việt": "Bật tất cả"],
        "Disable All": ["English": "Disable All", "Tiếng Việt": "Tắt tất cả"],
        "All skills": ["English": "All skills", "Tiếng Việt": "Tất cả Skill"],
        "All tools": ["English": "All tools", "Tiếng Việt": "Tất cả công cụ"],
        "Core Tools": ["English": "Core Tools", "Tiếng Việt": "Công cụ cốt lõi"],
        "New Skill": ["English": "New Skill", "Tiếng Việt": "Kỹ năng mới"],
        "No skills installed": ["English": "No skills installed", "Tiếng Việt": "Chưa cài kỹ năng nào"],
        "Share App Window": ["English": "Share App Window", "Tiếng Việt": "Chia sẻ cửa sổ app"],
        "Share Full Screen": ["English": "Share Full Screen", "Tiếng Việt": "Chia sẻ toàn màn hình"],
        "Share Selected Region": ["English": "Share Selected Region", "Tiếng Việt": "Chia sẻ vùng chọn"],
        "Share Camera": ["English": "Share Camera", "Tiếng Việt": "Chia sẻ camera"],
        "Stop Sharing": ["English": "Stop Sharing", "Tiếng Việt": "Dừng chia sẻ"],
        "Camera": ["English": "Camera", "Tiếng Việt": "Camera"],
        "Region": ["English": "Region", "Tiếng Việt": "Vùng"],
        "Name": ["English": "Name", "Tiếng Việt": "Tên"],
        "Agent name (optional)": ["English": "Agent name (optional)", "Tiếng Việt": "Tên trợ lý (không bắt buộc)"],
        "Edit System Prompt": ["English": "Edit System Prompt", "Tiếng Việt": "Sửa lời nhắc hệ thống"],
        "No skills": ["English": "No skills", "Tiếng Việt": "Không có Skill"],
        "No tools": ["English": "No tools", "Tiếng Việt": "Không có công cụ"],
        "Clear": ["English": "Clear", "Tiếng Việt": "Xóa trắng"],
        "Change Photo": ["English": "Change Photo", "Tiếng Việt": "Đổi ảnh"],
        "Default": ["English": "Default", "Tiếng Việt": "Mặc định"],
        "Search": ["English": "Search", "Tiếng Việt": "Tìm kiếm"],
        "Read": ["English": "Read", "Tiếng Việt": "Đọc"],
        "Write": ["English": "Write", "Tiếng Việt": "Ghi"],
        "List": ["English": "List", "Tiếng Việt": "Liệt kê"],
        "Find": ["English": "Find", "Tiếng Việt": "Tìm file"],
        "Grep": ["English": "Grep", "Tiếng Việt": "Tìm nội dung"],
        "Edit": ["English": "Edit", "Tiếng Việt": "Sửa"],
        "Calendar": ["English": "Calendar", "Tiếng Việt": "Lịch"],
        "Clipboard": ["English": "Clipboard", "Tiếng Việt": "Bảng tạm"],
        "App": ["English": "App", "Tiếng Việt": "Ứng dụng"],
        "Media": ["English": "Media", "Tiếng Việt": "Phát lại"],
        "Screenshot": ["English": "Screenshot", "Tiếng Việt": "Chụp màn hình"],
        "Browser": ["English": "Browser", "Tiếng Việt": "Trình duyệt"],
        "Local File Search": ["English": "Local File Search", "Tiếng Việt": "Tìm file cục bộ"],
        "Show Result": ["English": "Show Result", "Tiếng Việt": "Hiển thị kết quả"],
        "Skill Writer": ["English": "Skill Writer", "Tiếng Việt": "Tạo Skill"],
        "Exec": ["English": "Exec", "Tiếng Việt": "Chạy lệnh"],
        "Off": ["English": "Off", "Tiếng Việt": "Tắt"],
        "Low": ["English": "Low", "Tiếng Việt": "Thấp"],
        "Medium": ["English": "Medium", "Tiếng Việt": "Vừa"],
        "High": ["English": "High", "Tiếng Việt": "Cao"],
        "Auto-start Breaks": ["English": "Auto-start Breaks", "Tiếng Việt": "Tự động bắt đầu nghỉ"],
        "Auto-start Pomo": ["English": "Auto-start Pomo", "Tiếng Việt": "Tự động bắt đầu Pomodoro"],
        "tools": ["English": "tools", "Tiếng Việt": "công cụ"],
        "skills": ["English": "skills", "Tiếng Việt": "skill"],
        "Auto Hide": ["English": "Auto Hide", "Tiếng Việt": "Tự ẩn"],
        "Quit Notch": ["English": "Quit Notch", "Tiếng Việt": "Thoát Notch"],
        "Hide Notch": ["English": "Hide Notch", "Tiếng Việt": "Ẩn Notch"],
        "Show Notch": ["English": "Show Notch", "Tiếng Việt": "Hiện Notch"],
        "Show on One Screen": ["English": "Show on One Screen", "Tiếng Việt": "Hiện một màn hình"],
        "Show on All Screens": ["English": "Show on All Screens", "Tiếng Việt": "Hiện tất cả màn hình"],
        "Reposition": ["English": "Reposition", "Tiếng Việt": "Đặt lại vị trí"],
        "Settings…": ["English": "Settings…", "Tiếng Việt": "Cài đặt…"],
        "Quit": ["English": "Quit", "Tiếng Việt": "Thoát"],
        "Invisible": ["English": "Invisible", "Tiếng Việt": "Vô hình"],
        "Fullscreen": ["English": "Fullscreen", "Tiếng Việt": "Toàn màn hình"],
        "Invisible Always": ["English": "Always", "Tiếng Việt": "Luôn bật"],
        "Screen Display": ["English": "Screen Display", "Tiếng Việt": "Hiển thị màn hình"],
        "One Screen": ["English": "One", "Tiếng Việt": "Một"],
        "All Screens": ["English": "All", "Tiếng Việt": "Tất cả"],
        "User Profile": ["English": "User Profile", "Tiếng Việt": "Hồ sơ cá nhân"],
        "Memory": ["English": "Memory", "Tiếng Việt": "Bộ nhớ"],
        "User Profile (USER.md)": ["English": "User Profile (USER.md)", "Tiếng Việt": "Hồ sơ cá nhân (USER.md)"],
        "Memory (MEMORY.md)": ["English": "Memory (MEMORY.md)", "Tiếng Việt": "Bộ nhớ (MEMORY.md)"],
        "Save User Profile": ["English": "Save User Profile", "Tiếng Việt": "Lưu hồ sơ"],
        "Save Memory": ["English": "Save Memory", "Tiếng Việt": "Lưu bộ nhớ"],
        "Mode": ["English": "Mode", "Tiếng Việt": "Chế độ"],
        "Zen": ["English": "Zen", "Tiếng Việt": "Chìm đắm"],
        "Strict": ["English": "Strict", "Tiếng Việt": "Kỷ luật nghỉ"],
        "Sound": ["English": "Sound", "Tiếng Việt": "Âm thanh"],
        "Streak": ["English": "Streak", "Tiếng Việt": "Chuỗi"],
        "Today": ["English": "Today", "Tiếng Việt": "Hôm nay"],
        "Sessions": ["English": "Sessions", "Tiếng Việt": "Phiên"],
        "Average": ["English": "Average", "Tiếng Việt": "Trung bình"],
        "What are you working on?": ["English": "What are you working on?", "Tiếng Việt": "Bạn đang làm việc gì?"],
        "Tasks": ["English": "Tasks", "Tiếng Việt": "Nhiệm vụ"],
        "Add": ["English": "Add", "Tiếng Việt": "Thêm"],
        "No tasks yet": ["English": "No tasks yet", "Tiếng Việt": "Chưa có nhiệm vụ"],
        "Open tasks": ["English": "Open tasks", "Tiếng Việt": "Chưa xong"],
        "Completed tasks": ["English": "Completed", "Tiếng Việt": "Đã xong"],
        "Subscription": ["English": "Subscription", "Tiếng Việt": "Đăng ký"],
        "Gemini Live": ["English": "Gemini Live", "Tiếng Việt": "Gemini Live"],
        "Gemini Account": ["English": "Gemini Account", "Tiếng Việt": "Tài khoản Gemini"],
        "Talk": ["English": "Talk", "Tiếng Việt": "Trò chuyện"],
        "Floating orb window": [
            "English": "Floating orb window",
            "Tiếng Việt": "Cửa sổ orb nổi",
        ],
        "Show floating orb window when connected": [
            "English": "Show floating orb when session is connected",
            "Tiếng Việt": "Hiện cửa sổ orb nổi khi phiên đang kết nối",
        ],
        "Orb always on top": [
            "English": "Orb always on top",
            "Tiếng Việt": "Orb luôn nổi trên cửa sổ thường",
        ],
        "Show Notch in Dock when orb visible": [
            "English": "Show Notch in Dock while orb window is visible",
            "Tiếng Việt": "Hiện Notch trong Dock khi đang có cửa sổ orb",
        ],
        "Orb appearance": [
            "English": "Orb appearance",
            "Tiếng Việt": "Kiểu orb",
        ],
        "Orb style Ice": [
            "English": "Ice",
            "Tiếng Việt": "Băng",
        ],
        "Orb style Ember": [
            "English": "Ember",
            "Tiếng Việt": "Than lửa",
        ],
        "Orb style Nebula": [
            "English": "Nebula",
            "Tiếng Việt": "Tinh vân",
        ],
        "Orb style Aurora": [
            "English": "Aurora",
            "Tiếng Việt": "Cực quang",
        ],
        "Orb style Mono": [
            "English": "Mono",
            "Tiếng Việt": "Đơn sắc",
        ],
        "Orb style Particle Wave": [
            "English": "Particle Wave",
            "Tiếng Việt": "Sóng hạt",
        ],
        "Orb menu": ["English": "Orb", "Tiếng Việt": "Orb"],
        "Orb menu Show in Dock": [
            "English": "Show Notch in Dock while orb visible",
            "Tiếng Việt": "Hiện Notch trong Dock khi đang có orb",
        ],
        "Orb menu Open Talk settings": [
            "English": "Open Talk settings…",
            "Tiếng Việt": "Mở cài đặt Talk…",
        ],
        "Appearance": ["English": "Appearance", "Tiếng Việt": "Giao diện"],
        "Notch Pro": ["English": "Notch Pro", "Tiếng Việt": "Notch Pro"],
        "Subscribed": ["English": "Subscribed", "Tiếng Việt": "Đã đăng ký"],
        "Not subscribed": ["English": "Not subscribed", "Tiếng Việt": "Chưa đăng ký"],
        "Subscribe": ["English": "Subscribe", "Tiếng Việt": "Đăng ký"],
        "Restore Purchases": ["English": "Restore Purchases", "Tiếng Việt": "Khôi phục giao dịch"],
        "Connection Method": ["English": "Connection Method", "Tiếng Việt": "Kiểu kết nối"],
        "Account": ["English": "Account", "Tiếng Việt": "Tài khoản"],
        "Notch Account": ["English": "Notch Account", "Tiếng Việt": "Tài khoản Notch"],
        "Not signed in": ["English": "Not signed in", "Tiếng Việt": "Chưa đăng nhập"],
        "Manage your Notch account and Pro subscription.": [
            "English": "Manage your Notch account and Pro subscription.",
            "Tiếng Việt": "Quản lý tài khoản Notch và gói Pro.",
        ],
        "Your account has Notch Pro access.": [
            "English": "Your account has Notch Pro access.",
            "Tiếng Việt": "Tài khoản của bạn có quyền Notch Pro.",
        ],
        "Upgrade to Notch Pro to unlock Talk.": [
            "English": "Upgrade to Notch Pro to unlock Talk.",
            "Tiếng Việt": "Nâng cấp Notch Pro để mở khóa Talk.",
        ],
        "Sign in to verify Pro access and sync your subscription.": [
            "English": "Sign in to verify Pro access and sync your subscription.",
            "Tiếng Việt": "Đăng nhập để xác minh quyền Pro và đồng bộ gói đăng ký.",
        ],
        "Managed server uses your Notch Account.": [
            "English": "Managed server uses your Notch Account.",
            "Tiếng Việt": "Máy chủ được quản lý dùng Tài khoản Notch của bạn.",
        ],
        "Sign in and manage Pro from the Account tab.": [
            "English": "Sign in and manage Pro from the Account tab.",
            "Tiếng Việt": "Đăng nhập và quản lý Pro trong tab Tài khoản.",
        ],
        "Open Account Settings": [
            "English": "Open Account Settings",
            "Tiếng Việt": "Mở cài đặt Tài khoản",
        ],
        "Choose how Notch connects to Gemini Live across the app.": [
            "English": "Choose how Notch connects to Gemini Live across the app.",
            "Tiếng Việt": "Chọn cách Notch kết nối tới Gemini Live cho toàn bộ ứng dụng.",
        ],
        "Most people should use Notch Account. API key mode is best for advanced setups.": [
            "English": "Most people should use Notch Account. API key mode is best for advanced setups.",
            "Tiếng Việt": "Hầu hết mọi người nên dùng Tài khoản Notch. Chế độ API key phù hợp hơn cho thiết lập nâng cao.",
        ],
        "Your Gemini API Key": ["English": "Your Gemini API Key", "Tiếng Việt": "Gemini API Key của bạn"],
        "Save API key": ["English": "Save API key", "Tiếng Việt": "Lưu API key"],
        "This key is stored locally on your Mac and used directly by Notch.": [
            "English": "This key is stored locally on your Mac and used directly by Notch.",
            "Tiếng Việt": "Key này được lưu cục bộ trên máy Mac và được Notch dùng trực tiếp.",
        ],
        "Use secure browser sign-in. Notch will complete OAuth 2.0 + PKCE automatically.": [
            "English": "Use secure browser sign-in. Notch will complete OAuth 2.0 + PKCE automatically.",
            "Tiếng Việt": "Dùng đăng nhập an toàn trên trình duyệt. Notch sẽ tự hoàn tất OAuth 2.0 + PKCE.",
        ],
        "No URL or token setup required.": [
            "English": "No URL or token setup required.",
            "Tiếng Việt": "Không cần nhập URL hay token.",
        ],
        "Sign in here once and Talk will reuse this session everywhere in the app.": [
            "English": "Sign in here once and Talk will reuse this session everywhere in the app.",
            "Tiếng Việt": "Đăng nhập một lần ở đây, Talk sẽ dùng lại phiên này ở mọi nơi trong app.",
        ],
        "Continue in your browser. Notch will finish OAuth sign-in automatically.": [
            "English": "Continue in your browser. Notch will finish OAuth sign-in automatically.",
            "Tiếng Việt": "Tiếp tục trong trình duyệt. Notch sẽ tự hoàn tất đăng nhập OAuth.",
        ],
        "Use your own Gemini key if you prefer to connect directly.": [
            "English": "Use your own Gemini key if you prefer to connect directly.",
            "Tiếng Việt": "Dùng Gemini key riêng nếu bạn muốn kết nối trực tiếp.",
        ],
        "Signed in as": ["English": "Signed in as", "Tiếng Việt": "Đăng nhập với"],
        "Log in": ["English": "Log in", "Tiếng Việt": "Đăng nhập"],
        "Sign up": ["English": "Sign up", "Tiếng Việt": "Tạo tài khoản"],
        "Sign out": ["English": "Sign out", "Tiếng Việt": "Đăng xuất"],
        "Open Settings Tab": ["English": "Open Settings Tab", "Tiếng Việt": "Mở tab Cài đặt"],
        "Notch Pro is required to use Talk.": [
            "English": "Notch Pro is required to use Talk.",
            "Tiếng Việt": "Cần Notch Pro để dùng Talk.",
        ],
        "Notch Pro is required to use the hosted Gemini Live server.": [
            "English": "Notch Pro is required to use the hosted Gemini Live server.",
            "Tiếng Việt": "Cần Notch Pro để dùng máy chủ Gemini Live được Notch cung cấp.",
        ],
        "Create account on the web": [
            "English": "Create account on the web",
            "Tiếng Việt": "Tạo tài khoản trên web",
        ],
        "Sign in on the web": [
            "English": "Sign in on the web",
            "Tiếng Việt": "Đăng nhập trên web",
        ],
        "After you sign in on the web, Notch will return automatically.": [
            "English": "After you sign in on the web, Notch will return automatically.",
            "Tiếng Việt": "Sau khi bạn đăng nhập trên web, Notch sẽ tự quay lại.",
        ],
        "Copy-token flow (recommended): on the web sign-in page, the token is copied after login — open Notch, tap Paste from clipboard, then Sign in with token. Or sign in below with email and password.": [
            "English": "Copy-token flow (recommended): on the web sign-in page, the token is copied after login — open Notch, tap Paste from clipboard, then Sign in with token. Or sign in below with email and password.",
            "Tiếng Việt": "Nên dùng: sau khi đăng nhập trên web, token được copy — mở Notch, bấm Dán từ clipboard, rồi Đăng nhập bằng token. Hoặc đăng nhập bên dưới bằng email và mật khẩu.",
        ],
        "Session token": [
            "English": "Session token",
            "Tiếng Việt": "Token phiên",
        ],
        "Paste from clipboard": [
            "English": "Paste from clipboard",
            "Tiếng Việt": "Dán từ clipboard",
        ],
        "Sign in with token": [
            "English": "Sign in with token",
            "Tiếng Việt": "Đăng nhập bằng token",
        ],
        "Invalid or expired session token.": [
            "English": "Invalid or expired session token.",
            "Tiếng Việt": "Token không hợp lệ hoặc đã hết hạn.",
        ],
        "Buy Notch Pro": ["English": "Buy Notch Pro", "Tiếng Việt": "Mua Notch Pro"],
        "Refresh Pro status": [
            "English": "Refresh Pro status",
            "Tiếng Việt": "Cập nhật trạng thái Pro",
        ],
        "Sign in or refresh your Notch account to verify Pro access for Talk.": [
            "English": "Sign in or refresh your Notch account to verify Pro access for Talk.",
            "Tiếng Việt": "Đăng nhập hoặc cập nhật tài khoản Notch để xác minh quyền Pro cho Talk.",
        ],
        "Notch Pro access could not be verified. Refresh your account to continue using Talk.": [
            "English": "Notch Pro access could not be verified. Refresh your account to continue using Talk.",
            "Tiếng Việt": "Không thể xác minh quyền Notch Pro. Hãy cập nhật tài khoản để tiếp tục dùng Talk.",
        ],
        "Offline Pro grace period is active.": [
            "English": "Offline Pro grace period is active.",
            "Tiếng Việt": "Đang dùng thời gian gia hạn Pro khi offline.",
        ],
        "Pro status is expired. Refresh your account to verify access.": [
            "English": "Pro status is expired. Refresh your account to verify access.",
            "Tiếng Việt": "Trạng thái Pro đã hết hạn. Hãy cập nhật tài khoản để xác minh quyền truy cập.",
        ],
        "Pro status has not been verified yet.": [
            "English": "Pro status has not been verified yet.",
            "Tiếng Việt": "Trạng thái Pro chưa được xác minh.",
        ],
        "Weekly Activity": ["English": "Weekly Activity", "Tiếng Việt": "Hoạt động hàng tuần"],
        "Session Timing": ["English": "Session Timing", "Tiếng Việt": "Thời gian phiên"],
        "Automation": ["English": "Automation", "Tiếng Việt": "Tự động hóa"],
        "Allowed Websites": ["English": "Allowed Websites", "Tiếng Việt": "Trang web được cho phép"],
        "Auto-open on Focus Start": ["English": "Auto-open on Focus Start", "Tiếng Việt": "Tự động mở khi tập trung"],
        "Transition Sound": ["English": "Transition Sound", "Tiếng Việt": "Âm thanh chuyển đổi"],
        "Enable Notifications": ["English": "Enable Notifications", "Tiếng Việt": "Bật thông báo"],
        "Show Focus Timer in Menu Bar": ["English": "Show Focus Timer in Menu Bar", "Tiếng Việt": "Hiện đồng hồ Focus trên thanh menu"],
        "No allowed websites yet.": ["English": "No allowed websites yet.", "Tiếng Việt": "Chưa có trang web được cho phép."],
        "No auto-open URLs yet.": ["English": "No auto-open URLs yet.", "Tiếng Việt": "Chưa có URL tự động mở."],
        "e.g. music.youtube.com": ["English": "e.g. music.youtube.com", "Tiếng Việt": "ví dụ: music.youtube.com"],
        "e.g. notion.so or https://docs.google.com": ["English": "e.g. notion.so or https://docs.google.com", "Tiếng Việt": "ví dụ: notion.so hoặc https://docs.google.com"],
        "domains will never be blocked": ["English": "domains will never be blocked", "Tiếng Việt": "domain sẽ không bao giờ bị chặn"],
        "URLs will open on focus start": ["English": "URLs will open on focus start", "Tiếng Việt": "URL sẽ tự động mở khi bắt đầu tập trung"],
        "%d domains will never be blocked": ["English": "%d domains will never be blocked", "Tiếng Việt": "%d domain sẽ không bao giờ bị chặn"],
        "%d URLs will open on focus start": ["English": "%d URLs will open on focus start", "Tiếng Việt": "%d URL sẽ tự động mở khi bắt đầu tập trung"],
        "Accent": ["English": "Accent", "Tiếng Việt": "Màu nhấn"],
        "Display": ["English": "Display", "Tiếng Việt": "Hiển thị"],
        "Interaction": ["English": "Interaction", "Tiếng Việt": "Tương tác"],
        "Closed Notch Height": ["English": "Closed Notch Height", "Tiếng Việt": "Chiều cao notch đóng"],
        "System": ["English": "System", "Tiếng Việt": "Hệ thống"],
        "Auto-Collapse Delay": ["English": "Auto-Collapse Delay", "Tiếng Việt": "Độ trễ tự đóng"],
        "Connection": ["English": "Connection", "Tiếng Việt": "Kết nối"],
        "Saving...": ["English": "Saving...", "Tiếng Việt": "Đang lưu..."],
        "Model": ["English": "Model", "Tiếng Việt": "Mô hình"],
        "Untitled": ["English": "Untitled", "Tiếng Việt": "Chưa đặt tên"],
    ]

    static func get(_ key: String, lang: String) -> String {
        return dict[key]?[lang] ?? key
    }
}

// MARK: - Global Settings View
